package at.martinthedragon.nucleartech.datagen.localisation

import at.martinthedragon.nucleartech.CreativeTabs
import at.martinthedragon.nucleartech.LangKeys
import at.martinthedragon.nucleartech.Materials
import at.martinthedragon.nucleartech.TranslationKey
import at.martinthedragon.nucleartech.block.NTechBlocks
import at.martinthedragon.nucleartech.datagen.NuclearLanguageProviders
import at.martinthedragon.nucleartech.entity.EntityTypes
import at.martinthedragon.nucleartech.entity.attribute.Attributes
import at.martinthedragon.nucleartech.fluid.NTechFluids
import at.martinthedragon.nucleartech.fluid.trait.NTechFluidTraits
import at.martinthedragon.nucleartech.item.NTechItems
import at.martinthedragon.nucleartech.menu.MenuTypes
import at.martinthedragon.nucleartech.world.DamageSources
import net.minecraft.data.DataGenerator

class JaJpLanguageProvider(dataGenerator: DataGenerator) : NuclearLanguageProvider(dataGenerator, NuclearLanguageProviders.JA_JP) {
    override fun validate() {
        val additionalLangKeys = LangKeys.javaClass.declaredFields.mapNotNull { it.trySetAccessible(); it.get(LangKeys) as? String }.filter(TranslationKey::isValidKey)
        if (!translations.keys.containsAll(additionalLangKeys)) {
            val missingLangKeys = additionalLangKeys subtract translations.keys
            val errorMessage = StringBuilder().appendLine("The following additional translation keys from LangKeys are not added to the translation definition:")
            for (missing in missingLangKeys) errorMessage.appendLine(missing.prependIndent())
            throw IllegalStateException(errorMessage.toString())
        }

        NuclearLanguageProviders.keys = translations.keys.toSet()
        NuclearLanguageProviders.materialTranslations = materialTranslations.toMap()
    }

    override fun translate() {
        addCreativeTab(CreativeTabs.Parts, "NTMの資源と素材")
        addCreativeTab(CreativeTabs.Items, "NTMの機械アイテムや燃料")
        addCreativeTab(CreativeTabs.Templates, "NTMのテンプレート")
        addCreativeTab(CreativeTabs.Blocks, "NTMのブロック")
        addCreativeTab(CreativeTabs.Machines, "NTMの機械")
        addCreativeTab(CreativeTabs.Bombs, "NTMの爆弾")
        addCreativeTab(CreativeTabs.Rocketry, "NTMのミサイルや衛星")
        addCreativeTab(CreativeTabs.Consumables, "NTMのギアと消耗品")
        addCreativeTab(CreativeTabs.Miscellaneous, "NTM その他")

        addMaterials()

        addBlock(NTechBlocks.scorchedUraniumOre, "焦げたウラン鉱石")
        addBlock(NTechBlocks.thoriumOre, "トリウム鉱石")
        addBlock(NTechBlocks.oilDeposit, "オイルデポジット")
        addBlockDesc(NTechBlocks.oilDeposit, "あなたはこれを採掘すべきではなかったのです。\nさあ、デリックを手に入れろ。")
        addBlock(NTechBlocks.emptyOilDeposit, "空のオイルデポジット")
        addBlock(NTechBlocks.oilSand, "オイルサンド")
        addBlock(NTechBlocks.australianOre, "Australian Ore")
        addBlockDesc(NTechBlocks.australianOre, "Australium Ore")
        addBlock(NTechBlocks.weidite, "ウィダニウム")
        addBlockDesc(NTechBlocks.weidite, "ウィダニウム鉱石")
        addBlock(NTechBlocks.reiite, "レイウム")
        addBlockDesc(NTechBlocks.reiite, "レイウム鉱石")
        addBlock(NTechBlocks.brightblendeOre, "ブライトブレンド鉱石")
        addBlockDesc(NTechBlocks.brightblendeOre, "アナティウム鉱石")
        addBlock(NTechBlocks.dellite, "デライト")
        addBlockDesc(NTechBlocks.dellite, "ダファーゴン鉱石")
        addBlock(NTechBlocks.dollarGreenMineral, "ドラーグリーンミネラル")
        addBlockDesc(NTechBlocks.dollarGreenMineral, "バティシアム鉱石")
        addBlock(NTechBlocks.rareEarthOre, "レアアース鉱石")
        addBlock(NTechBlocks.netherUraniumOre, "ネザーウラニウム鉱石")
        addBlock(NTechBlocks.scorchedNetherUraniumOre, "焦げたネザーウラニウム鉱石")
        addBlock(NTechBlocks.netherPlutoniumOre, "ネザープルトニウム鉱石")
        addBlock(NTechBlocks.netherTungstenOre, "ネザータングステン鉱石")
        addBlock(NTechBlocks.netherSulfurOre, "ネザー硫黄鉱石")
        addBlock(NTechBlocks.netherPhosphorusOre, "ネザーリン鉱石")
        addBlock(NTechBlocks.netherSchrabidiumOre, "ネザージュラビジウム鉱石")
        addBlock(NTechBlocks.meteorUraniumOre, "隕石ウラニウム鉱石")
        addBlock(NTechBlocks.meteorThoriumOre, "隕石トリウム鉱石")
        addBlock(NTechBlocks.meteorTitaniumOre, "隕石チタン鉱石")
        addBlock(NTechBlocks.meteorSulfurOre, "隕石硫黄鉱石")
        addBlock(NTechBlocks.meteorCopperOre, "隕石銅鉱石")
        addBlock(NTechBlocks.meteorTungstenOre, "隕石タングステン鉱石")
        addBlock(NTechBlocks.meteorAluminiumOre, "隕石アルミニウム鉱石")
        addBlock(NTechBlocks.meteorLeadOre, "隕石鉛鉱石")
        addBlock(NTechBlocks.meteorLithiumOre, "隕石リチウム鉱石")
        addBlock(NTechBlocks.starmetalOre, "スターメタル鉱石")
        addBlock(NTechBlocks.trixite, "トリキサイト")
        addBlock(NTechBlocks.basaltSulfurOre, "硫黄玄武岩")
        addBlock(NTechBlocks.basaltFluoriteOre, "フローライト玄武岩")
        addBlock(NTechBlocks.basaltAsbestosOre, "アスベスト玄武岩")
        addBlock(NTechBlocks.basaltVolcanicGemOre, "ジェム玄武岩")

        addBlock(NTechBlocks.scorchedDeepslateUraniumOre, "焦げた深層ウラン鉱石")
        addBlock(NTechBlocks.deepslateOilDeposit, "深層石油鉱床")
        addBlockDesc(NTechBlocks.deepslateOilDeposit, "こんな深くまで来たのに何をすればいいかわかってないの...?w")
        addBlock(NTechBlocks.emptyDeepslateOilDeposit, "空の深層石油鉱床")
        addBlock(NTechBlocks.deepslateAustralianOre, "深層オーストラリウム鉱石")
        addBlockDesc(NTechBlocks.deepslateAustralianOre, "オーストラリウムの鉱石")
        addBlock(NTechBlocks.deepslateRareEarthOre, "深層レアアース鉱石")

        addBlock(NTechBlocks.whitePhosphorusBlock, "白リンの塊")
        addBlock(NTechBlocks.redPhosphorusBlock, "赤リンの塊")
        addBlock(NTechBlocks.yellowcakeBlock, "イエローケーキブロック")
        addBlock(NTechBlocks.scrapBlock, "スクラップブロック")
        addBlock(NTechBlocks.electricalScrapBlock, "電気スクラップブロック")
        addBlock(NTechBlocks.insulatorRoll, "絶縁ロール")
        addBlock(NTechBlocks.fiberglassRoll, "ファイバーグラスロール")
        addBlock(NTechBlocks.trinititeBlock, "トリニタイトブロック")
        addBlock(NTechBlocks.nuclearWasteBlock, "核廃棄物ブロック")
        addBlock(NTechBlocks.schrabidiumCluster, "ジュラビジウム結晶")
        addBlock(NTechBlocks.euphemiumEtchedSchrabidiumCluster, "含ユーフェミウムシュラビジウム結晶")
        addBlock(NTechBlocks.deshReinforcedBlock, "強化デッシュのブロック")

        addBlock(NTechBlocks.titaniumDecoBlock, "チタニウムデコブロック")
        addBlock(NTechBlocks.redCopperDecoBlock, "赤銅デコブロック")
        addBlock(NTechBlocks.tungstenDecoBlock, "タングステンデコブロック")
        addBlock(NTechBlocks.aluminiumDecoBlock, "アルミニウムデコブロック")
        addBlock(NTechBlocks.steelDecoBlock, "スチールデコブロック")
        addBlock(NTechBlocks.leadDecoBlock, "鉛デコブロック")
        addBlock(NTechBlocks.berylliumDecoBlock, "ベリリウムデコブロック")
        addBlock(NTechBlocks.asbestosRoof, "アスベストルーフ")
        addBlock(NTechBlocks.hazmatBlock, "危険物ブロック")
        addBlock(NTechBlocks.meteorite, "隕石")
        addBlock(NTechBlocks.meteoriteCobblestone, "隕石の丸石")
        addBlock(NTechBlocks.brokenMeteorite, "壊れた隕石")
        addBlock(NTechBlocks.hotMeteoriteCobblestone, "熱い隕石の丸石")
        addBlock(NTechBlocks.meteoriteTreasure, "隕石の宝")
        addBlock(NTechBlocks.steelBeam, "スチールビーム")
        addBlock(NTechBlocks.steelScaffold, "スチール製足場")
        addBlock(NTechBlocks.steelGrate, "スチール格子")

        addBlock(NTechBlocks.glowingMushroom, "光るマッシュルーム")
        addBlock(NTechBlocks.glowingMushroomBlock, "光るマッシュルームブロック")
        addBlock(NTechBlocks.glowingMushroomStem, "光るマッシュルームの茎")
        addBlock(NTechBlocks.deadGrass, "枯草")
        addBlock(NTechBlocks.glowingMycelium, "光る菌糸体")
        addBlock(NTechBlocks.trinitite, "トリニタイト鉱石")
        addBlock(NTechBlocks.redTrinitite, "赤トリニタイト鉱石")
        addBlock(NTechBlocks.charredLog, "焦げた丸太")
        addBlock(NTechBlocks.charredPlanks, "焦げた板材")

        addBlock(NTechBlocks.slakedSellafite, "弱セラファイト")
        addBlock(NTechBlocks.sellafite, "セラファイト")
        addBlock(NTechBlocks.hotSellafite, "熱いセラファイト")
        addBlock(NTechBlocks.boilingSellafite, "煮え滾るセラファイト")
        addBlock(NTechBlocks.blazingSellafite, "燃え盛るセラファイト")
        addBlock(NTechBlocks.infernalSellafite, "獄熱のセラファイト")
        addBlock(NTechBlocks.sellafiteCorium, "セラファイト-コリウム")

        addBlock(NTechBlocks.corium, "コリウム")
        addBlock(NTechBlocks.corebblestone, "コレブルストーン")

        addBlock(NTechBlocks.siren, "サイレン")
        addBlock(NTechBlocks.safe, "金庫")
        addBlock(NTechBlocks.steamPressBase, "スチームプレス")
        addBlock(NTechBlocks.steamPressFrame, "スチームプレス")
        addBlock(NTechBlocks.steamPressTop, "蒸気プレス")
        addBlock(NTechBlocks.blastFurnace, "溶鉱炉")
        addBlock(NTechBlocks.combustionGenerator, "燃焼発電機")
        addBlock(NTechBlocks.electricFurnace, "電気炉")
        addBlock(NTechBlocks.shredder, "シュレッダー")
        addBlock(NTechBlocks.assembler, "組立機")
        addBlock(NTechBlocks.chemPlant, "化学プラント")
        addBlock(NTechBlocks.turbine, "蒸気タービン")
        addBlock(NTechBlocks.smallCoolingTower, "補助冷却塔")
        addBlock(NTechBlocks.largeCoolingTower, "冷却塔")
        addBlockDesc(NTechBlocks.turbine, "効率: 85%%")
        addBlock(NTechBlocks.oilDerrick, "石油掘削機")
        addBlock(NTechBlocks.pumpjack, "パンプジャック")
        addBlockDesc11(NTechBlocks.pumpjack, "地球の蚊め")
        addBlock(NTechBlocks.radar, "レーダー")
        addBlock(NTechBlocks.centrifuge, "遠心分離機")
        addBlock(NTechBlocks.ironAnvil, "鉄の金床")
        addBlock(NTechBlocks.leadAnvil, "鉛の金床")
        addBlock(NTechBlocks.steelAnvil, "スチールの金床")
        addBlock(NTechBlocks.meteoriteAnvil, "メテオライトの金床")
        addBlock(NTechBlocks.starmetalAnvil, "スターメタルの金床")
        addBlock(NTechBlocks.ferrouraniumAnvil, "鉄化ウランの金床")
        addBlock(NTechBlocks.bismuthAnvil, "ビスマスの金床")
        addBlock(NTechBlocks.schrabidateAnvil, "鉄化ジュラビジデートの金床")
        addBlock(NTechBlocks.dineutroniumAnvil, "ダイニュートロニウムの金床")
        addBlock(NTechBlocks.murkyAnvil, "Murky Anvil")

        addBlock(NTechBlocks.decoRbmkBlock, "RBMKのデコブロック")
        addBlock(NTechBlocks.decoRbmkSmoothBlock, "滑らかなRBMKのデコブロック")

        addBlock(NTechBlocks.rbmkColumn, "RBMK構造柱")
        addBlock(NTechBlocks.rbmkRod, "RBMK燃料棒")
        addBlock(NTechBlocks.rbmkModeratedRod, "RBMK 減速燃料棒")
        addBlock(NTechBlocks.rbmkReaSimRod, "RBMK燃料棒 (ReaSim)")
        addBlock(NTechBlocks.rbmkModeratedReaSimRod, "RBMK減速燃料棒 (ReaSim)")
        addBlock(NTechBlocks.rbmkReflector, "RBMK中性子反射材")
        addBlock(NTechBlocks.rbmkModerator, "RBMK黒鉛制御装置")
        addBlock(NTechBlocks.rbmkAbsorber, "RBMKホウ素中性子吸収材")
        addBlock(NTechBlocks.rbmkBoilerColumn, "RBMK蒸気経路部品")
        addBlock(NTechBlocks.rbmkBoiler, "RBMKボイラー")
        addBlock(NTechBlocks.rbmkBlank, "RBMK構造柱")
        addBlock(NTechBlocks.rbmkManualControlRod, "RBMK燃料棒制御装置")
        addBlock(NTechBlocks.rbmkModeratedControlRod, "RBMK燃料棒制御装置モデレーター")
        addBlock(NTechBlocks.rbmkAutoControlRod, "RBMK自動燃料棒制御装置")
        addBlock(NTechBlocks.rbmkSteamConnector, "RBMK蒸気制御装置")
        addBlock(NTechBlocks.rbmkInlet, "RBMK ReaSim 水注入口")
        addBlock(NTechBlocks.rbmkOutlet, "RBMK ReaSim 蒸気出口")
        addBlock(NTechBlocks.rbmkConsole, "RBMKコンソール")
        addBlock(NTechBlocks.rbmkDebris, "RBMK廃棄物")
        addBlock(NTechBlocks.rbmkBurningDebris, "熱いRBMK廃棄物")
        addBlock(NTechBlocks.rbmkRadioactiveDebris, "燃え盛るRBMK廃棄物")

        addBlock(NTechBlocks.coatedCable, "被覆赤銅ケーブル")
        addBlock(NTechBlocks.coatedUniversalFluidDuct, "被覆流体ダクト")

        addBlock(NTechBlocks.littleBoy, "リトルボーイ")
        addBlock(NTechBlocks.fatMan, "ファットマン")
        addBlock(NTechBlocks.volcanoCore, "火山の心臓")

        addBlock(NTechBlocks.launchPad, "ミサイル発射台")
        addBlock(NTechBlocks.launchPadPart, "ミサイル発射台部品")

        addBlock(NTechBlocks.genericMultiBlockPart, "マルチブロック構造部品")
        addBlock(NTechBlocks.genericMultiBlockPort, "マルチブロック構造ポート")
        addBlock(NTechBlocks.oilPipe, "石油パイプ")

        addBlock(NTechFluids.spentSteam.block, "低圧蒸気")
        addBlock(NTechFluids.steam.block, "蒸気")
        addBlock(NTechFluids.steamHot.block, "濃密蒸気")
        addBlock(NTechFluids.steamSuperHot.block, "高密蒸気")
        addBlock(NTechFluids.steamUltraHot.block, "超高密蒸気")
        addBlock(NTechFluids.oil.block, "原油")
        addBlock(NTechFluids.gas.block, "天然ガス")
        addBlock(NTechFluids.uraniumHexafluoride.block, "六フッ化ウラン")
        addBlock(NTechFluids.corium.block, "コリウム")
        addBlock(NTechFluids.coolant.block, "冷却材")
        addBlock(NTechFluids.volcanicLava.block, "火山溶岩")

        addItem(NTechItems.rawThorium, "トリウムの原石")
        addItem(NTechItems.rawRareEarth, "レアアースの原石")
        addItem(NTechItems.rawTrixite, "トリキサイトの原石")

        addItemDesc(NTechItems.neptuniumIngot, "あれは私のお気に入りだ！！")
        addItemDesc(NTechItems.tantaliumIngot, "'タンタル'")
        addItemDesc(NTechItems.tantaliumNugget, "'タンタル'")
        addItemDesc(NTechItems.schraraniumIngot, "シュラビジウム核変換炉でウランから作れるゾ！")
        addItemDesc(NTechItems.combineSteelIngot, "＊国民の保護もしよう！＊")
        addItemDesc(NTechItems.ghiorsium336Ingot, "シーボーギウムの同胞。")
        addItemDesc(NTechItems.ghiorsium336Nugget, "シーボーギウムの同胞。")
        addItem(NTechItems.lanthanumIngot, "準安定ランタンインゴット")
        addItemDesc(NTechItems.euphemiumIngot, "不思議で特別な元素")
        addItem(NTechItems.whitePhosphorusIngot, "白リン棒")

        addItem(NTechItems.semtexBar, "セムテックス")
        addItemDesc(
            NTechItems.semtexBar,
            "セムテックス - プラスチック爆薬\n" +
                    "多機能で高性能な爆薬\n" +
                    "食べれる...?"
        )

        addItem(NTechItems.lithiumCube, "リチウム")
        addItem(NTechItems.solidFuelCube, "固形燃料")
        addItem(NTechItems.solidRocketFuelCube, "固形ロケット用燃料")

        addItem(NTechItems.fiberglassSheet, "グラスファイバーシート")
        addItemDesc(NTechItems.fiberglassSheet, "高繊維、高強度、必要なものすべて。")
        addItem(NTechItems.asbestosSheet, "石綿シート")
        addItemDesc(NTechItems.asbestosSheet, "§o「人生と自信喪失とアスベストでいっぱい。それは空気とともにやってくる。」")

        addItem(NTechItems.lesserAustraliumBillet, "小さいオーストラリウム鋼片")
        addItem(NTechItems.greaterAustraliumBillet, "大きいオーストラリウム鋼片")
        addItem(NTechItems.po210BeBillet, "Po210Beの鋼片")
        addItem(NTechItems.ra226BeBillet, "Ra226Beの鋼片")
        addItem(NTechItems.pu238BeBillet, "Pu238Beの鋼片")
        addItem(NTechItems.zirconiumBillet, "ジルコニウムの鋼片")
        addItem(NTechItems.bismuthZfbBillet, "蒼鉛ZFBの鋼片")
        addItem(NTechItems.pu241ZfbBillet, "プルトニウム241ZFBの鋼片")
        addItem(NTechItems.reactorGradeAmericiumZfbBillet, "原子炉級アメリシウムZFBの鋼片")
        addItem(NTechItems.yharoniteBillet, "イハロナイトの鋼片")
        addItem(NTechItems.flashgoldBillet, "閃光金の鋼片")
        addItem(NTechItems.flashleadBillet, "閃光鉛の鋼片")
        addItemDesc(NTechItems.flashleadBillet, "原子が崩壊し、対消滅を起こし、パイ中間子を放出し、ミュー粒子が崩壊し、原子核の融合をで新しい元素を作る。")

        addItem(NTechItems.mercuryDroplet, "水銀の雫")
        addItem(NTechItems.mercuryBottle, "水銀入りのボトル")

        addItem(NTechItems.coke, "コークス")
        addItem(NTechItems.lignite, "褐炭")
        addItem(NTechItems.ligniteBriquette, "褐炭煉炭")

        addItem(NTechItems.sulfur, "硫黄")
        addItem(NTechItems.niter, "硝石")
        addItem(NTechItems.fluorite, "蛍石")
        addItem(NTechItems.quartzPowder, "クォーツの粉")
        addItem(NTechItems.yellowcake, "イエローケーキ")
        addItem(NTechItems.chlorophytePowder, "クロロファイトの粉")
        addItem(NTechItems.neodymiumPowder, "ネオジムの粉")
        addItem(NTechItems.niobiumPowder, "ニオブの粉")
        addItem(NTechItems.ceriumPowder, "セリウムの粉")
        addItemDesc(NTechItems.asbestosPowder, "§o„くんくん... - ｺﾞﾌｪっｺﾞﾎっごほっ“")
        addItem(NTechItems.enchantmentPowder, "魔法の粉")
        addItem(NTechItems.cloudResidue, "雲の残骸")
        addItem(NTechItems.thermonuclearAshes, "§c§l〝熱核の灰〟")
        addItem(NTechItems.semtexMix, "セムテックス混合物")
        addItem(NTechItems.deshMix, "デッシュ混合粉")
        addItem(NTechItems.deshReadyMix, "デッシュレディ™混合粉")
        addItem(NTechItems.nitaniumMix, "二タン混合粉")
        addItem(NTechItems.sparkMix, "スパーク混合粉")
        addItem(NTechItems.meteoritePowder, "隕石混合粉")
        addItemDesc(NTechItems.euphemiumPowder, "粉砕されたピンク\nいちごのお味")
        addItem(NTechItems.desaturatedRedstone, "不全の赤石")
        addItem(NTechItems.dust, "粉")
        addItemDesc(NTechItems.dust, "粉は嫌い！")
        addItem(NTechItems.tinyLithiumPowder, "リチウムの細粉")
        addItem(NTechItems.tinyNeodymiumPowder, "ネオジムの細粉")
        addItem(NTechItems.tinyCobaltPowder, "コバルトの細粉")
        addItem(NTechItems.tinyNiobiumPowder, "ニオブの細粉")
        addItem(NTechItems.tinyCeriumPowder, "セリウムの細粉")
        addItem(NTechItems.tinyLanthanumPowder, "アクチニウムの細粉")
        addItem(NTechItems.tinyMeteoritePowder, "隕石の細粉")
        addItem(NTechItems.redPhosphorus, "赤燐")
        addItemDesc(NTechItems.redPhosphorus, "多機能爆弾で使用:\n炎炎の炎に還れ...")
        addItem(NTechItems.cryoPowder, "クライオパウダー")
        addItem(NTechItems.poisonPowder, "毒の粉")
        addItemDesc(NTechItems.poisonPowder, "多機能爆弾で使用:\n毒性注意！")
        addItem(NTechItems.thermite, "酸化鉄")
        addItem(NTechItems.energyPowder, "エネルギーの粉")

        addItem(NTechItems.cordite, "コルダイト")
        addItem(NTechItems.ballistite, "バリスタイト")

        addItem(NTechItems.rareEarthCrystals, "レアアースクリスタル")
        addItem(NTechItems.redPhosphorusCrystals, "赤燐クリスタル")
        addItem(NTechItems.trixiteCrystals, "トリキサイトクリスタル")

        addItem(NTechItems.volcanicGem, "火山の宝石")

        addItem(NTechItems.neodymiumFragment, "ネオジムの破片")
        addItem(NTechItems.cobaltFragment, "コバルトの破片")
        addItem(NTechItems.niobiumFragment, "ニオブの破片")
        addItem(NTechItems.ceriumFragment, "セリウムの破片")
        addItem(NTechItems.lanthanumFragment, "ランタンの破片")
        addItem(NTechItems.actiniumFragment, "アクチニウムの破片")
        addItem(NTechItems.meteoriteFragment, "隕石の破片")

        addItem(NTechItems.biomass, "バイオマス")
        addItem(NTechItems.compressedBiomass, "圧縮バイオマス")

        addItemDesc(
            NTechItems.euphemiumNugget,
            "小さな金属のピンクの破片\n" +
                    "この物質の性質はまだ未知\n" +
                    "注意深く扱え..."
        )

        addItem(NTechItems.neutronReflector, "中性子反射板")
        addItem(NTechItems.mixedPlate, "合金板")
        addItem(NTechItems.paAAlloyPlate, "PaA合金板")
        addItem(NTechItems.insulator, "断熱材")
        addItem(NTechItems.kevlarCeramicCompound, "ケブラーセラミック合金")
        addItem(NTechItems.dalekaniumPlate, "Angry Metal")
        addItem(NTechItems.deshCompoundPlate, "デッシュ合金板")
        addItem(NTechItems.euphemiumCompoundPlate, "ユーフェミウム合金板")
        addItem(NTechItems.dineutroniumCompoundPlate, "ジニュートロニウム合金板")
        addItem(NTechItems.copperPanel, "銅厚板")

        addItem(NTechItems.highSpeedSteelBolt, "高速鋼ボルト")
        addItem(NTechItems.tungstenBolt, "タングステンボルト")
        addItem(NTechItems.reinforcedTurbineShaft, "強化タービンシャフト")

        addItem(NTechItems.hazmatCloth, "防護布")
        addItem(NTechItems.advancedHazmatCloth, "強化防護布")
        addItem(NTechItems.leadReinforcedHazmatCloth, "鉛加工防護布")
        addItem(NTechItems.fireProximityCloth, "耐火布")
        addItem(NTechItems.activatedCarbonFilter, "活性炭フィルター")

        addItem(NTechItems.superConductor, "超伝導体")
        addItem(NTechItems.highTemperatureSuperConductor, "400万 高温超伝導体")

        addItem(NTechItems.copperCoil, "銅コイル")
        addItem(NTechItems.ringCoil, "リングコイル")
        addItem(NTechItems.superConductingCoil, "超伝導コイル")
        addItem(NTechItems.superConductingRingCoil, "超伝導リングコイル")
        addItem(NTechItems.goldCoil, "金コイル")
        addItem(NTechItems.goldRingCoil, "金リングコイル")
        addItem(NTechItems.heatingCoil, "加熱コイル")
        addItem(NTechItems.highTemperatureSuperConductingCoil, "400万 高音超伝導コイル")

        addItem(NTechItems.steelTank, "鋼鉄タンク")
        addItem(NTechItems.motor, "モーター")
        addItem(NTechItems.centrifugeElement, "遠心素子")
        addItem(NTechItems.centrifugeTower, "遠心塔")
        addItem(NTechItems.deeMagnets, "D字磁石")
        addItem(NTechItems.flatMagnet, "平坦磁石")
        addItem(NTechItems.cyclotronTower, "原子破壊塔")
        addItem(NTechItems.breedingReactorCore, "増殖炉コア")
        addItem(NTechItems.rtgUnit, "放射性同位体熱電気転換器")
        addItem(NTechItems.thermalDistributionUnit, "熱的分布ユニット")
        addItem(NTechItems.endothermicDistributionUnit, "吸熱分布ユニット")
        addItem(NTechItems.exothermicDistributionUnit, "発熱分布ユニット")
        addItem(NTechItems.gravityManipulator, "反重力操作パーツ")
        addItem(NTechItems.steelPipes, "鋼鉄パイプ")
        addItem(NTechItems.titaniumDrill, "チタンドリル")
        addItem(NTechItems.photovoltaicPanel, "ソーラーパネル")
        addItem(NTechItems.chlorinePinwheel, "塩素フィン")
        addItem(NTechItems.telepad, "テレパッド")
        addItem(NTechItems.entanglementKit, "量子もつれキット")
        addItemDesc(
            NTechItems.entanglementKit,
            "テレポーターの素材\n" +
                    "ベリリウム加工済スキャナで\n" +
                    "次元間転移ができる"
        )
        addItem(NTechItems.stabilizerComponent, "安定器素材")
        addItem(NTechItems.emitterComponent, "発信器素材")
        addItem(NTechItems.aluminiumCap, "アルミの蓋")
        addItem(NTechItems.smallSteelShell, "小型鋼鉄シェル")
        addItem(NTechItems.smallAluminiumShell, "小型アルミシェル")
        addItem(NTechItems.bigSteelShell, "大型鋼鉄シェル")
        addItem(NTechItems.bigAluminiumShell, "大型アルミシェル")
        addItem(NTechItems.bigTitaniumShell, "大型チタンシェル")
        addItem(NTechItems.flatSteelCasing, "平たい鋼鉄ケーシング")
        addItem(NTechItems.smallSteelGridFins, "大型鋼鉄グリッドフィン")
        addItem(NTechItems.largeSteelFins, "大が型鋼鉄フィン")
        addItem(NTechItems.smallTitaniumFins, "小型チタンフィン")
        addItem(NTechItems.steelSphere, "球状の鋼鉄")
        addItem(NTechItems.steelPedestal, "鋼鉄の台座")
        addItem(NTechItems.dysfunctionalNuclearReactor, "〝機能不全の原子炉〟")
        addItem(NTechItems.largeSteelRotor, "大型鋼鉄ローター")
        addItem(NTechItems.generatorBody, "発電機機体")
        addItem(NTechItems.titaniumBlade, "チタンブレード")
        addItem(NTechItems.tungstenReinforcedBlade, "タングステン強化済ブレード")
        addItem(NTechItems.titaniumSteamTurbine, "チタンスチームタービン")
        addItem(NTechItems.reinforcedTurbofanBlades, "強化タービンブレード")
        addItem(NTechItems.generatorFront, "発電機前部")
        addItem(NTechItems.toothpicks, "つまようじ")
        addItem(NTechItems.ductTape, "ダクトテープ")
        addItem(NTechItems.clayCatalyst, "粘度触媒")
        addItem(NTechItems.smallMissileAssembly, "小型ミサイル素材")

        addItem(NTechItems.smallWarhead, "小型弾頭")
        addItem(NTechItems.mediumWarhead, "中型弾頭")
        addItem(NTechItems.largeWarhead, "大型弾頭")
        addItem(NTechItems.smallIncendiaryWarhead, "小型可燃弾頭")
        addItem(NTechItems.mediumIncendiaryWarhead, "中型可燃弾頭")
        addItem(NTechItems.largeIncendiaryWarhead, "大型可燃弾頭")
        addItem(NTechItems.smallClusterWarhead, "小型クラスター弾頭")
        addItem(NTechItems.mediumClusterWarhead, "中型クラスター弾頭")
        addItem(NTechItems.largeClusterWarhead, "大型クラスター弾頭")
        addItem(NTechItems.smallBunkerBusterWarhead, "小型バンカーバスター弾頭")
        addItem(NTechItems.mediumBunkerBusterWarhead, "中型バンカーバスター弾頭")
        addItem(NTechItems.largeBunkerBusterWarhead, "大型バンカーバスター弾頭")
        addItem(NTechItems.nuclearWarhead, "核弾頭")
        addItem(NTechItems.thermonuclearWarhead, "〝熱核弾頭〟")
        addItem(NTechItems.endothermicWarhead, "低温弾頭")
        addItem(NTechItems.exothermicWarhead, "高熱弾頭")

        addItem(NTechItems.smallFuelTank, "小型燃料タンク")
        addItem(NTechItems.mediumFuelTank, "中型燃料タンク")
        addItem(NTechItems.largeFuelTank, "大型燃料タンク")

        addItem(NTechItems.smallThruster, "小型スラスタ")
        addItem(NTechItems.mediumThruster, "中型スラスタ")
        addItem(NTechItems.largeThruster, "大型スラスタ")
        addItem(NTechItems.lvnNuclearRocketEngine, "LV-N原子力ロケットエンジン")

        addItem(NTechItems.satelliteBase, "人工衛星ベース")
        addItem(NTechItems.highGainOpticalCamera, "高画質光学カメラ")
        addItem(NTechItems.m700SurveyScanner, "M700資源スキャナ")
        addItem(NTechItems.radarDish, "レーダーシャーレ")
        addItem(NTechItems.deathRay, "デスレイ")
        addItem(NTechItems.xeniumResonator, "キセニウム共鳴器")

        addItem(NTechItems.size10Connector, "10大コネクタ")
        addItem(NTechItems.size15Connector, "15大コネクタ")
        addItem(NTechItems.size20Connector, "20大コネクタ")

        addItem(NTechItems.hunterChopperCockpit, "ハンターチョッパーコックピット")
        addItem(NTechItems.emplacementGun, "定置銃")
        addItem(NTechItems.hunterChopperBody, "ハンターチョッパー機体")
        addItem(NTechItems.hunterChopperTail, "ハンターチョッパー尾部")
        addItem(NTechItems.hunterChopperWing, "ハンターチョッパー羽部")
        addItem(NTechItems.hunterChopperRotorBlades, "ハンターチョッパーローターブレード")
        addItem(NTechItems.combineScrapMetal, "CMBスクラップ")

        addItem(NTechItems.heavyHammerHead, "ヘビーハンマーヘッド")
        addItem(NTechItems.heavyAxeHead, "ヘビーアックスヘッド")
        addItem(NTechItems.reinforcedPolymerHandle, "強化プラスチックハンドル")

        addItem(NTechItems.basicCircuitAssembly, "基本回路素材")
        addItem(NTechItems.basicCircuit, "基本回路")
        addItem(NTechItems.enhancedCircuit, "強化回路")
        addItem(NTechItems.advancedCircuit, "発展回路")
        addItem(NTechItems.overclockedCircuit, "高周波回路")
        addItem(NTechItems.highPerformanceCircuit, "高性能回路")
        addItem(NTechItems.militaryGradeCircuitBoardTier1, "軍用基板 (ティア1)")
        addItem(NTechItems.militaryGradeCircuitBoardTier2, "軍用基板 (ティア2)")
        addItem(NTechItems.militaryGradeCircuitBoardTier3, "軍用基板 (ティア3)")
        addItem(NTechItems.militaryGradeCircuitBoardTier4, "軍用基板 (ティア4)")
        addItem(NTechItems.militaryGradeCircuitBoardTier5, "軍用基板 (ティア5)")
        addItem(NTechItems.militaryGradeCircuitBoardTier6, "軍用基板 (ティア6)")

        addItem(NTechItems.revolverMechanism, "リボルバー機構")
        addItem(NTechItems.advancedRevolverMechanism, "強化リボルバー機構")
        addItem(NTechItems.rifleMechanism, "ライフル機構")
        addItem(NTechItems.advancedRifleMechanism, "強化ライフル機構")
        addItem(NTechItems.launcherMechanism, "ランチャー機構")
        addItem(NTechItems.advancedLauncherMechanism, "強化ランチャー機構")
        addItem(NTechItems.highTechWeaponMechanism, "高技術兵器機構")

        addItem(NTechItems.point357MagnumPrimer, ".357 マグナム雷管 (x16)")
        addItem(NTechItems.point44MagnumPrimer, ".44 マグナム雷管 (x16)")
        addItem(NTechItems.smallCaliberPrimer, "小カリバー雷管 (x24)")
        addItem(NTechItems.largeCaliberPrimer, "大カリバー雷管 (x8)")
        addItem(NTechItems.buckshotPrimer, "霰弾雷管 (x8)")

        addItem(NTechItems.point357MagnumCasing, ".357 マグナムケーシング (x16)")
        addItem(NTechItems.point44MagnumCasing, ".44 マグナムケーシング (x16)")
        addItem(NTechItems.smallCaliberCasing, "小カリバーケーシング (x24)")
        addItem(NTechItems.largeCaliberCasing, "大カリバーケーシング (x8)")
        addItem(NTechItems.buckshotCasing, "霰弾ケーシング (x8)")

        addItem(NTechItems.ironBulletAssembly, "鉄弾素材")
        addItem(NTechItems.leadBulletAssembly, "鉛弾素材")
        addItem(NTechItems.glassBulletAssembly, "ガラス弾素材")
        addItem(NTechItems.goldBulletAssembly, "金弾素材")
        addItem(NTechItems.schrabidiumBulletAssembly, "シュラビジウム弾素材")
        addItem(NTechItems.nightmareBulletAssembly, "タングステン弾素材")
        addItem(NTechItems.deshBulletAssembly, "デッシュ弾素材")
        addItem(NTechItems.point44MagnumAssembly, ".44 マグナム素材")
        addItem(NTechItems.nineMmAssembly, "9mm 素材")
        addItem(NTechItems.fivePoint56mmAssembly, "5.56mm 素材")
        addItem(NTechItems.point22LRAssembly, ".22 LR 素材")
        addItem(NTechItems.point5mmAssembly, ".5mm 素材")
        addItem(NTechItems.point50AEAssembly, ".50 AE 素材")
        addItem(NTechItems.point50BMGAssembly, ".50 BMG 素材")

        addItem(NTechItems.silverBulletCasing, "銀弾ケーシング")
        addItem(NTechItems.twelvePoint8cmStarmetalHighEnergyShell, "12.8cm 星鉄高エネルギーシェル")
        addItem(NTechItems.twelvePoint8cmNuclearShell, "12.8cm 原子力シェル")
        addItem(NTechItems.twelvePoint8cmDUShell, "12.8cm DUシェル")

        addItem(NTechItems.cableDrum, "ケーブルドラム")
        addItemDesc(NTechItems.cableDrum, "右クリックで電柱を接続")
        addItem(NTechItems.paintingOfACartoonPony, "かわいい子馬の絵")
        addItemDesc(NTechItems.paintingOfACartoonPony, "黄色い馬が青い馬を倒す。当然の事実だ!")
        addItem(NTechItems.conspiracyTheory, "陰謀論")
        addItemDesc(NTechItems.conspiracyTheory, "鉄骨梁はジェット燃料を溶かせまい...")
        addItem(NTechItems.politicalTopic, "政治的話題")
        addItemDesc(NTechItems.politicalTopic, "ドナルドダックはアメリカに壁を建てる")
        addItem(NTechItems.ownOpinion, "自分の意見")
        addItemDesc(NTechItems.ownOpinion, "大切にしろよ...")

        addItem(NTechItems.explosivePellets, "爆発ペレット")
        addItemDesc(NTechItems.explosivePellets, "多機能爆弾で使用:\n爆発力強化")
        addItem(NTechItems.leadPellets, "鉛ペレット")
        addItem(NTechItems.flechettes, "ダーツ")
        addItem(NTechItems.poisonGasCartridge, "毒ガスカートリッジ")
        addItemDesc(NTechItems.poisonGasCartridge, "多機能爆弾で使用:\n*ゴホゴホ*... たすけて!!")
        addItem(NTechItems.magnetron, "磁器管")
        addItem(NTechItems.denseCoalCluster, "高密度石炭")
        addItem(NTechItems.burntBark, "焦げ落ちた樹皮")
        addItemDesc(NTechItems.burntBark, "爆ぜし金樫の樹皮")
        addItem(NTechItems.machineUpgradeTemplate, "マシン強化テンプレート")

        addItem(NTechItems.blankRune, "空の触媒母型")
        addItem(NTechItems.isaRune, "石炭の触媒母型")
        addItem(NTechItems.dagazRune, "汎用触媒母型")
        addItem(NTechItems.hagalazRune, "粗悪な触媒母型")
        addItem(NTechItems.jeraRune, "乗法触媒母型")
        addItem(NTechItems.thurisazRune, "加法触媒母型")

        addItem(NTechItems.burnedOutQuadSchrabidiumFuelRod, "燃え尽きたシュラビジウム燃料")
        addItemDesc(NTechItems.burnedOutQuadSchrabidiumFuelRod, "わずかに奇妙な新物質が含まれている...")

        addItem(NTechItems.scrap, "ゴミクズ")
        addItem(NTechItems.hotDepletedUraniumFuel, "冷めていない劣化ウラン燃料")
        addItem(NTechItems.hotDepletedThoriumFuel, "冷めていない劣化トリウム燃料")
        addItem(NTechItems.hotDepletedPlutoniumFuel, "冷めていない劣化プルトニウム燃料")
        addItem(NTechItems.hotDepletedMOXFuel, "冷めていない劣化MOX燃料")
        addItem(NTechItems.hotDepletedSchrabidiumFuel, "冷めていない劣化シュラビジウム燃料")
        addItem(NTechItems.depletedUraniumFuel, "劣化ウラン燃料")
        addItem(NTechItems.depletedThoriumFuel, "劣化トリウム燃料")
        addItem(NTechItems.depletedPlutoniumFuel, "劣化プルトニウム燃料")
        addItem(NTechItems.depletedMOXFuel, "劣化MOX燃料")
        addItem(NTechItems.depletedSchrabidiumFuel, "劣化シュラビジウム燃料")
        addItem(NTechItems.trinitite, "ハリトンチキ")
        addItem(NTechItems.nuclearWaste, "核廃棄物")
        addItem(NTechItems.tinyNuclearWaste, "小さな核廃棄物")

        addItem(NTechItems.crystalHorn, "結晶角")
        addItemDesc(NTechItems.crystalHorn, "本物の角だ")
        addItem(NTechItems.charredCrystal, "焦げたクリスタル")
        addItemDesc(NTechItems.charredCrystal, "本物の角だ、おかしいな？")

        addItem(NTechItems.battery, "バッテリー")
        addItem(NTechItems.redstonePowerCell, "レッドストーン電池")
        addItem(NTechItems.sixfoldRedstonePowerCell, "六束レッドストーン電池")
        addItem(NTechItems.twentyFourFoldRedstonePowerCell, "二十四束レッドストーン電池")
        addItem(NTechItems.advancedBattery, "発展バッテリー")
        addItem(NTechItems.advancedPowerCell, "発展電池")
        addItem(NTechItems.quadrupleAdvancedPowerCell, "四束電池")
        addItem(NTechItems.twelveFoldAdvancedPowerCell, "十二束電池")
        addItem(NTechItems.lithiumBattery, "リチウムイオンバッテリー")
        addItem(NTechItems.lithiumPowerCell, "リチウムイオン電池")
        addItem(NTechItems.tripleLithiumPowerCell, "三束リチウムイオン電池")
        addItem(NTechItems.sixfoldLithiumPowerCell, "六束リチウムイオン電池")
        addItem(NTechItems.schrabidiumBattery, "シュラビジウムバッテリー")
        addItem(NTechItems.schrabidiumPowerCell, "シュラビジウム電池")
        addItem(NTechItems.doubleSchrabidiumPowerCell, "二束シュラビジウム電池")
        addItem(NTechItems.quadrupleSchrabidiumPowerCell, "四束シュラビジウム電池")
        addItem(NTechItems.sparkBattery, "スパークバッテリー")
        addItem(NTechItems.offBrandSparkBattery, "偽スパークバッテリー")
        addItem(NTechItems.sparkPowerCell, "スパーク電池")
        addItem(NTechItems.sparkArcaneCarBattery, "スパーク難解電池")
        addItem(NTechItems.sparkArcaneEnergyStorageArray, "スパーク難解エネルギーストレージ配列")
        addItem(NTechItems.sparkArcaneMassEnergyVoid, "スパーク高エネルギー虚")
        addItem(NTechItems.sparkArcaneDiracSea, "スパーク電池〝ディラックの海〟")
        addItem(NTechItems.sparkSolidSpaceTimeCrystal, "スパーク〝固形宇宙時間クリスタル〟")
        addItem(NTechItems.sparkLudicrousPhysicsDefyingEnergyStorageUnit, "スパーク - ばかばかしい、物理学を完全に無視し蹂躙したエネルギーストレージユニット")
        addItem(NTechItems.infiniteBattery, "無限バッテリー")
        addItem(NTechItems.singleUseBattery, "使い捨てバッテリー")
        addItem(NTechItems.largeSingleUseBattery, "大型使い捨てバッテリー")
        addItem(NTechItems.potatoBattery, "芋電池")
        addItem(NTechItems.steamPoweredEnergyStorageTank, "蒸気エネルギーストレージタンク")
        addItem(NTechItems.largeSteamPoweredEnergyStorageTank, "大型蒸気エネルギーストレージタンク")

        addItem(NTechItems.stoneFlatStamp, "空のスタンプ (石)")
        addItem(NTechItems.stonePlateStamp, "板スタンプ (石)")
        addItem(NTechItems.stoneWireStamp, "ワイヤスタンプ (石)")
        addItem(NTechItems.stoneCircuitStamp, "回路スタンプ (石)")
        addItem(NTechItems.ironFlatStamp, "空のスタンプ (鉄)")
        addItem(NTechItems.ironPlateStamp, "板スタンプ (鉄)")
        addItem(NTechItems.ironWireStamp, "ワイヤスタンプ (鉄)")
        addItem(NTechItems.ironCircuitStamp, "回路スタンプ (鉄)")
        addItem(NTechItems.steelFlatStamp, "空のスタンプ (鋼鉄)")
        addItem(NTechItems.steelPlateStamp, "板スタンプ (鋼鉄)")
        addItem(NTechItems.steelWireStamp, "ワイヤスタンプ (鋼鉄)")
        addItem(NTechItems.steelCircuitStamp, "回路スタンプ (鋼鉄)")
        addItem(NTechItems.titaniumFlatStamp, "空のスタンプ (チタン)")
        addItem(NTechItems.titaniumPlateStamp, "板スタンプ (チタン)")
        addItem(NTechItems.titaniumWireStamp, "ワイヤスタンプ (チタン)")
        addItem(NTechItems.titaniumCircuitStamp, "回路スタンプ (チタン)")
        addItem(NTechItems.obsidianFlatStamp, "空のスタンプ (黒曜石)")
        addItem(NTechItems.obsidianPlateStamp, "板スタンプ (黒曜石)")
        addItem(NTechItems.obsidianWireStamp, "ワイヤスタンプ (黒曜石)")
        addItem(NTechItems.obsidianCircuitStamp, "回路スタンプ (黒曜石)")
        addItem(NTechItems.schrabidiumFlatStamp, "空のスタンプ (シュラビジウム)")
        addItem(NTechItems.schrabidiumPlateStamp, "板スタンプ (シュラビジウム)")
        addItem(NTechItems.schrabidiumWireStamp, "ワイヤスタンプ (シュラビジウム)")
        addItem(NTechItems.schrabidiumCircuitStamp, "回路スタンプ (シュラビジウム)")

        addItem(NTechItems.screwdriver, "スクリュードライバー")
        addItemDesc(NTechItems.screwdriver, "ヒューズの代替に...")
        addItem(NTechItems.deshScrewdriver, "デッシュのスクリュードライバー")

        addItem(NTechItems.speedUpgradeMk1, "速度強化 Mk.I")
        addItem(NTechItems.speedUpgradeMk2, "速度強化 Mk.II")
        addItem(NTechItems.speedUpgradeMk3, "速度強化 Mk.III")
        addItem(NTechItems.powerSavingUpgradeMk1, "電力消費強化 Mk.I")
        addItem(NTechItems.powerSavingUpgradeMk2, "電力消費強化 Mk.II")
        addItem(NTechItems.powerSavingUpgradeMk3, "電力消費強化 Mk.III")
        addItem(NTechItems.overdriveUpgradeMk1, "オーバードライブ Mk.I")
        addItem(NTechItems.overdriveUpgradeMk2, "オーバードライブ Mk.II")
        addItem(NTechItems.overdriveUpgradeMk3, "オーバードライブ Mk.III")
        addItem(NTechItems.afterBurnUpgradeMk1, "アフターバーナー Mk.I")
        addItem(NTechItems.afterBurnUpgradeMk2, "アフターバーナー Mk.II")
        addItem(NTechItems.afterBurnUpgradeMk3, "アフターバーナー Mk.III")

        addItem(NTechItems.aluminiumShredderBlade, "アルミシュレッダーブレード")
        addItem(NTechItems.goldShredderBlade, "金のシュレッダーブレード")
        addItem(NTechItems.ironShredderBlade, "鉄のシュレッダーブレード")
        addItem(NTechItems.steelShredderBlade, "鋼鉄のシュレッダーブレード")
        addItem(NTechItems.titaniumShredderBlade, "チタンのシュレッダーブレード")
        addItem(NTechItems.advancedAlloyShredderBlade, "強化合金のシュレッダーブレード")
        addItem(NTechItems.combineSteelShredderBlade, "CMB鋼のシュレッダーブレード")
        addItem(NTechItems.schrabidiumShredderBlade, "シュラビジウムのシュレッダーブレード")
        addItem(NTechItems.deshShredderBlade, "デッシュシュレッダーブレード")

        addItem(NTechItems.rbmkLid, "RBMKカバーパネル")
        addItem(NTechItems.rbmkGlassLid, "RBMKガラスカバーパネル")

        addItem(NTechItems.rbmkPelletBalefire, "ベールファイア燃料ペレット")
        addItem(NTechItems.rbmkPelletBalefireGold, "輝金燃料ペレット")
        addItem(NTechItems.rbmkPelletDrx, "§cディガンマ燃料ペレット§r")
        addItem(NTechItems.rbmkPelletFlashlead, "輝鉛燃料ペレット")
        addItem(NTechItems.rbmkPelletHea241, "HEA-241 燃料ペレット")
        addItem(NTechItems.rbmkPelletHea242, "HEA-242 燃料ペレット")
        addItem(NTechItems.rbmkPelletHeaus, "HEAus 燃料ペレット")
        addItem(NTechItems.rbmkPelletHen, "HEN 燃料ペレット")
        addItem(NTechItems.rbmkPelletHes, "HEP-239 燃料ペレット")
        addItem(NTechItems.rbmkPelletHep239, "HEP-241 燃料ペレット")
        addItem(NTechItems.rbmkPelletHep241, "HEU-233 燃料ペレット")
        addItem(NTechItems.rbmkPelletHeu233, "HEU-235 燃料ペレット")
        addItem(NTechItems.rbmkPelletHeu235, "HES 燃料ペレット")
        addItem(NTechItems.rbmkPelletLea, "LEA 燃料ペレット")
        addItem(NTechItems.rbmkPelletLeaus, "LEAus 燃料ペレット")
        addItem(NTechItems.rbmkPelletLep, "LEP 燃料ペレット")
        addItem(NTechItems.rbmkPelletLes, "LES 燃料ペレット")
        addItem(NTechItems.rbmkPelletMea, "MEA 燃料ペレット")
        addItem(NTechItems.rbmkPelletMen, "MEN 燃料ペレット")
        addItem(NTechItems.rbmkPelletMep, "MEP 燃料ペレット")
        addItem(NTechItems.rbmkPelletMes, "MES 燃料ペレット")
        addItem(NTechItems.rbmkPelletMeu, "MEU 燃料ペレット")
        addItem(NTechItems.rbmkPelletMox, "MOX 燃料ペレット")
        addItem(NTechItems.rbmkPelletPo210Be, "Po210Be 中性子源ペレット")
        addItem(NTechItems.rbmkPelletPu238Be, "Pu238Be 中性子源ペレット")
        addItem(NTechItems.rbmkPelletRa226Be, "Ra226Be 中性子源ペレット")
        addItem(NTechItems.rbmkPelletThMeu, "ThMEU 燃料ペレット")
        addItem(NTechItems.rbmkPelletUeu, "NU 燃料ペレット")
        addItem(NTechItems.rbmkPelletZfbAmMix, "Fuel Grade Americium ZFB ペレット")
        addItem(NTechItems.rbmkPelletZfbBismuth, "Bismuth ZFB ペレット")
        addItem(NTechItems.rbmkPelletZfbPu241, "Pu-241 ZFB ペレット")

        addItem(NTechItems.emptyRBMKRod, "空のRBMK燃料棒")
        addItem(NTechItems.rbmkRodBalefire, "§aベールファイアRBMK燃料棒")
        addItem(NTechItems.rbmkRodBalefireGold, "輝金RBMK燃料棒")
        addItem(NTechItems.rbmkRodDrx, "§cディガンマRBMK燃料棒§r")
        addItem(NTechItems.rbmkRodFlashlead, "輝鉛RBMK燃料棒")
        addItem(NTechItems.rbmkRodHea241, "HEA-241 RBMK燃料棒")
        addItem(NTechItems.rbmkRodHea242, "HEA-242 RBMK燃料棒")
        addItem(NTechItems.rbmkRodHeaus, "HEAus RBMK燃料棒")
        addItem(NTechItems.rbmkRodHen, "HEN RBMK燃料棒")
        addItem(NTechItems.rbmkRodHes, "HES RBMK燃料棒")
        addItem(NTechItems.rbmkRodHep239, "HEP-239 RBMK燃料棒")
        addItem(NTechItems.rbmkRodHep241, "HEP-241 RBMK燃料棒")
        addItem(NTechItems.rbmkRodHeu233, "HEU-233 RBMK燃料棒")
        addItem(NTechItems.rbmkRodHeu235, "HEU-235 RBMK燃料棒")
        addItem(NTechItems.rbmkRodLea, "LEA RBMK燃料棒")
        addItem(NTechItems.rbmkRodLeaus, "LEAus RBMK燃料棒")
        addItem(NTechItems.rbmkRodLep, "LEP-239 RBMK燃料棒")
        addItem(NTechItems.rbmkRodLes, "LES RBMK燃料棒")
        addItem(NTechItems.rbmkRodMea, "MEA RBMK燃料棒")
        addItem(NTechItems.rbmkRodMen, "MEN RBMK燃料棒")
        addItem(NTechItems.rbmkRodMep, "MEP-239 RBMK燃料棒")
        addItem(NTechItems.rbmkRodMes, "MES RBMK燃料棒")
        addItem(NTechItems.rbmkRodMeu, "MEU RBMK燃料棒")
        addItem(NTechItems.rbmkRodMox, "MOX RBMK燃料棒")
        addItem(NTechItems.rbmkRodPo210Be, "Po210Be RBMK中性子源棒")
        addItem(NTechItems.rbmkRodPu238Be, "Pu238Be RBMK中性子源棒")
        addItem(NTechItems.rbmkRodRa226Be, "Ra226Be RBMK中性子源棒")
        addItem(NTechItems.rbmkRodThMeu, "ThMEU RBMK燃料棒")
        addItem(NTechItems.rbmkRodUeu, "NU RBMK燃料棒")
        addItem(NTechItems.rbmkRodZfbAmMix, "Fuel Grade Americium RBMK ZFBロッド")
        addItem(NTechItems.rbmkRodZfbBismuth, "Bismuth RBMK ZFBロッド")
        addItem(NTechItems.rbmkRodZfbPu241, "Pu-241 RBMK ZFBロッド")

        addItem(NTechItems.meltdownTool, "〝ディアトロフ〟メルトダウンツール")

        addItem(NTechItems.graphiteDebris, "高熱グラファイト片")
        addItem(NTechItems.metalDebris, "壊れた鉄棒")
        addItem(NTechItems.fuelDebris, "RBMK燃料廃棄物")

        addItem(NTechItems.machineTemplateFolder, "マシンテンプレートフォルダ")
        addItemDesc(
            NTechItems.machineTemplateFolder,
            "組立テンプレート: 紙 + 染料\n" +
                    "流体ID: 鉄板 + 染料\n" +
                    "プレススタンプ: 空のスタンプ\n" +
                    "サイレントラック: 鋼板 + 断熱材"
        )

        addItem(NTechItems.sirenTrackHatchSiren, "Hatch Siren")
        addItem(NTechItems.sirenTrackAutopilotDisconnected, "Autopilot Disconnected")
        addItem(NTechItems.sirenTrackAMSSiren, "AMS Siren")
        addItem(NTechItems.sirenTrackBlastDoorAlarm, "Blast Door Alarm")
        addItem(NTechItems.sirenTrackAPCSiren, "APC Siren")
        addItem(NTechItems.sirenTrackKlaxon, "Klaxon")
        addItem(NTechItems.sirenTrackVaultDoorAlarm, "Vault Door Alarm")
        addItem(NTechItems.sirenTrackSecurityAlert, "Security Alert")
        addItem(NTechItems.sirenTrackStandardSiren, "Standard Siren")
        addItem(NTechItems.sirenTrackClassicSiren, "Classic Siren")
        addItem(NTechItems.sirenTrackBankAlarm, "Bank Alarm")
        addItem(NTechItems.sirenTrackBeepSiren, "Beep Siren")
        addItem(NTechItems.sirenTrackContainerAlarm, "Container Alarm")
        addItem(NTechItems.sirenTrackSweepSiren, "Sweep Siren")
        addItem(NTechItems.sirenTrackMissileSiloSiren, "Missile Silo Siren")
        addItem(NTechItems.sirenTrackAirRaidSiren, "Air Raid Siren")
        addItem(NTechItems.sirenTrackNostromoSelfDestruct, "Nostromo Self Destruct")
        addItem(NTechItems.sirenTrackEASAlarmScreech, "EAS Alarm Screech")
        addItem(NTechItems.sirenTrackAPCPass, "APC Pass")
        addItem(NTechItems.sirenTrackRazortrainHorn, "Razortrain Horn")

        addItem(NTechItems.fluidIdentifier, "流体ID: %s")
        addItemDesc(NTechItems.fluidIdentifier, "流体ダクトに右クリックで流体を指定\nシフト右クリックで隣接するすべてのダクトに流体を指定")

        addItem(NTechItems.assemblyTemplate, "組立テンプレート: %s")
        addItem(NTechItems.chemTemplate, "化学テンプレート: %s")

        run {
            val usedInLittleBoy = "リトルボーイで使用"
            addItem(NTechItems.neutronShieldingLittleBoy, "中性子遮断板")
            addItemDesc(NTechItems.neutronShieldingLittleBoy, usedInLittleBoy)
            addItem(NTechItems.subcriticalUraniumTarget, "未臨界ウラン235ターゲット")
            addItemDesc(NTechItems.subcriticalUraniumTarget, usedInLittleBoy)
            addItem(NTechItems.uraniumProjectile, "ウラン235発射体")
            addItemDesc(NTechItems.uraniumProjectile, usedInLittleBoy)
            addItem(NTechItems.propellantLittleBoy, "プロペラ")
            addItemDesc(NTechItems.propellantLittleBoy, usedInLittleBoy)
            addItem(NTechItems.bombIgniterLittleBoy, "発火者")
            addItemDesc(NTechItems.bombIgniterLittleBoy, usedInLittleBoy)
        }
        addItem(NTechItems.bundleOfImplosionPropellant, "爆縮推進剤の束")
        addItemDesc(NTechItems.bundleOfImplosionPropellant, "ファットマンとツァーリ・ボンバで使用")
        addItem(NTechItems.bombIgniterFatMan, "発火者")
        addItemDesc(NTechItems.bombIgniterFatMan, "ファットマンで使用")
        addItem(NTechItems.plutoniumCore, "プルトニウムコア")
        addItemDesc(NTechItems.plutoniumCore, "ファットマンとアイビー・マイクとツァーリ・ボンバで使用")
        addItem(NTechItems.detonator, "雷管")
        addItemDesc(NTechItems.detonator, "シフト右クリで位置を保存し、\n右クリで爆破")
        addItem(NTechItems.multiDetonator, "マルチ雷管")
        addItemDesc(NTechItems.multiDetonator, "シフト右クリックで位置を追加、右クリックで爆破！\n10個まで")
        addItem(NTechItems.littleBoyKit, "リトルボーイキット")
        addItem(NTechItems.fatManKit, "ファットマンキット")

        addItem(NTechItems.designator, "短距離照準器")
        addItem(NTechItems.antiBallisticMissile, "長距離対弾道ミサイル")
        addItem(NTechItems.antiBallisticMissileShort, "短距離対弾道ミサイル")
        addItem(NTechItems.heMissile, "高爆発ミサイル")
        addItem(NTechItems.incendiaryMissile, "焼夷ミサイル")
        addItem(NTechItems.clusterMissile, "クラスターミサイル")
        addItem(NTechItems.bunkerBusterMissile, "バンカーバスターミサイル")
        addItem(NTechItems.strongMissile, "強化爆発ミサイル")
        addItem(NTechItems.strongIncendiaryMissile, "強化焼夷ミサイル")
        addItem(NTechItems.strongClusterMissile, "強化クラスターミサイル")
        addItem(NTechItems.strongBunkerBusterMissile, "強化バンカーバスターミサイル")
        addItem(NTechItems.burstMissile, "バーストミサイル")
        addItem(NTechItems.infernoMissile, "爆裂ミサイル Mk.II")
        addItem(NTechItems.rainMissile, "爆薬の雨ミサイル")
        addItem(NTechItems.drillMissile, "ドリルミサイル")
        addItem(NTechItems.nuclearMissile, "核ミサイル")
        addItem(NTechItems.tectonicMissile, "地殻ミサイル")
        addItemDesc(NTechItems.tectonicMissile, "原子力爆発で火山を呼び起こせ！")

        addItem(NTechItems.meteorRemote, "隕石操作機")
        addItemDesc(NTechItems.meteorRemote, "右クリで隕石召喚")
        addItem(NTechItems.oilDetector, "油田探知機")
        addItemDesc(NTechItems.oilDetector, "右クリックで大きな油田を見つける")
        addItem(NTechItems.rbmkLinker, "RBMKコンソールリンクデバイス")
        addItemDesc(NTechItems.rbmkLinker, "シフト右クリでRBMKの位置を保存、もう一度シフト右クリでクレーンかコンソールとリンクできます")
        addItem(NTechItems.geigerCounter, "放射能測定機")

        addItem(NTechItems.ivBag, "IVバッグ")
        addItem(NTechItems.bloodBag, "血袋")
        addItem(NTechItems.emptyExperienceBag, "空の経験値バッグ")
        addItem(NTechItems.experienceBag, "経験値バッグ")
        addItem(NTechItems.radAway, "ラドアウェイ")
        addItem(NTechItems.strongRadAway, "強ラドアウェイ")
        addItem(NTechItems.eliteRadAway, "エリートラドアウェイ")

        addItem(NTechItems.hazmatHelmet, "防護ヘルメット")
        addItem(NTechItems.hazmatChestplate, "防護チェストプレート")
        addItem(NTechItems.hazmatLeggings, "防護レギンス")
        addItem(NTechItems.hazmatBoots, "防護ブーツ")
        addItem(NTechItems.advancedHazmatHelmet, "強化防護ヘルメット")
        addItem(NTechItems.advancedHazmatChestplate, "強化防護チェストプレート")
        addItem(NTechItems.advancedHazmatLeggings, "強化防護レギンス")
        addItem(NTechItems.advancedHazmatBoots, "強化防護ブーツ")
        addItem(NTechItems.reinforcedHazmatHelmet, "高性能防護ヘルメット")
        addItem(NTechItems.reinforcedHazmatChestplate, "高性能防護チェストプレート")
        addItem(NTechItems.reinforcedHazmatLeggings, "高性能防護レギンス")
        addItem(NTechItems.reinforcedHazmatBoots, "高性能防護ブーツ")
        addItem(NTechItems.titaniumHelmet, "チタンヘルメット")
        addItem(NTechItems.titaniumChestplate, "チタンチェストプレート")
        addItem(NTechItems.titaniumLeggings, "チタンレギンス")
        addItem(NTechItems.titaniumBoots, "チタンブーツ")
        addItem(NTechItems.steelHelmet, "スチールヘルメット")
        addItem(NTechItems.steelChestplate, "スチールチェストプレート")
        addItem(NTechItems.steelLeggings, "スチールレギンス")
        addItem(NTechItems.steelBoots, "スチールブーツ")
        addItem(NTechItems.advancedAlloyHelmet, "強化合金ヘルメット")
        addItem(NTechItems.advancedAlloyChestplate, "強化合金チェストプレート")
        addItem(NTechItems.advancedAlloyLeggings, "強化合金レギンス")
        addItem(NTechItems.advancedAlloyBoots, "強化合金ブーツ")
        addItem(NTechItems.combineSteelHelmet, "CMBヘルメット")
        addItem(NTechItems.combineSteelChestplate, "CMBチェストプレート")
        addItem(NTechItems.combineSteelLeggings, "CMBレギンス")
        addItem(NTechItems.combineSteelBoots, "CMBブーツ")
        addItem(NTechItems.paAAlloyChestplate, "PaA合金ヘルメット")
        addItem(NTechItems.paAAlloyLeggings, "PaA合金レギンス")
        addItem(NTechItems.paAAlloyBoots, "PaA合金ブーツ")
        addItem(NTechItems.schrabidiumHelmet, "シュラビジウムヘルメット")
        addItem(NTechItems.schrabidiumChestplate, "シュラビジウムチェストプレート")
        addItem(NTechItems.schrabidiumLeggings, "シュラビジウムレギンス")
        addItem(NTechItems.schrabidiumBoots, "シュラビジウムブーツ")

        addItem(NTechItems.polaroid, "〝ポラロイド〟")

        addItem(NTechFluids.spentSteam.bucket, "低圧蒸気バケツ")
        addItem(NTechFluids.steam.bucket, "蒸気バケツ")
        addItem(NTechFluids.steamHot.bucket, "濃密蒸気バケツ")
        addItem(NTechFluids.steamSuperHot.bucket, "高密蒸気バケツ")
        addItem(NTechFluids.steamUltraHot.bucket, "超高密蒸気バケツ")
        addItem(NTechFluids.gas.bucket, "天然ガスバケツに")
        addItem(NTechFluids.oil.bucket, "原油バケツ")
        addItem(NTechFluids.uraniumHexafluoride.bucket, "六フッ化ウランバケツ")
        addItem(NTechFluids.corium.bucket, "コリウムバケツ")
        addItem(NTechFluids.coolant.bucket, "冷却材バケツ")
        addItem(NTechFluids.volcanicLava.bucket, "火山性溶岩バケツ")

        addItem(NTechItems.creativeNuclearExplosionSpawner, "核爆発スポナー")
        addItemDesc(NTechItems.creativeNuclearExplosionSpawner, "Manufactured by CakeCo\nEast Spawn Rd 2, 68-419 RetroMC")

        addEntityType(EntityTypes.clusterFragment, "ボムレット")
        addEntityType(EntityTypes.falloutRain, "黒い雨")
        addEntityType(EntityTypes.meteor, "隕石")
        addEntityType(EntityTypes.missileBunkerBuster, "バンカーバスター")
        addEntityType(EntityTypes.missileBunkerBusterStrong, "強化バンカーバスター")
        addEntityType(EntityTypes.missileBurst, "バーストミサイル")
        addEntityType(EntityTypes.missileCluster, "クラスターミサイル")
        addEntityType(EntityTypes.missileClusterStrong, "強化クラスターミサイル")
        addEntityType(EntityTypes.missileDrill, "ドリルミサイル")
        addEntityType(EntityTypes.missileHE, "高爆発ミサイル")
        addEntityType(EntityTypes.missileHEStrong, "強化高爆発ミサイル")
        addEntityType(EntityTypes.missileIncendiary, "焼夷ミサイル")
        addEntityType(EntityTypes.missileIncendiaryStrong, "強化焼夷ミサイル")
        addEntityType(EntityTypes.missileInferno, "爆裂ミサイル G.R.N. Mk.II")
        addEntityType(EntityTypes.missileNuclear, "核ミサイル")
        addEntityType(EntityTypes.missileRain, "クラスター")
        addEntityType(EntityTypes.missileTectonic, "地殻ミサイル")
        addEntityType(EntityTypes.mushroomCloud, "きのこ雲")
        addEntityType(EntityTypes.nuclearExplosion, "核爆発")
        addEntityType(EntityTypes.oilSpill, "漏出油")
        addEntityType(EntityTypes.rbmkDebris, "RBMK廃棄物")
        addEntityType(EntityTypes.shrapnel, "破片")
        addEntityType(EntityTypes.volcanicShrapnel, "火山岩")

        addEntityTypeWithSpawnEgg(EntityTypes.nuclearCreeper, NTechItems.nuclearCreeperSpawnEgg, "Nuclear Creeper")

        addMenuType(MenuTypes.sirenMenu, "Siren")
        addMenuType(MenuTypes.safeMenu, "Safe")
        addMenuType(MenuTypes.anvilMenu, "Anvil Tier %s")
        addMenuType(MenuTypes.steamPressMenu, "Steam Press")
        addMenuType(MenuTypes.blastFurnaceMenu, "Blast Furnace")
        addMenuType(MenuTypes.combustionGeneratorMenu, "Combustion Generator")
        addMenuType(MenuTypes.electricFurnaceMenu, "Electric Furnace")
        addMenuType(MenuTypes.shredderMenu, "Shredder")
        addMenuType(MenuTypes.assemblerMenu, "Assembler")
        addMenuType(MenuTypes.chemPlantMenu, "Chemical Plant")
        addMenuType(MenuTypes.turbineMenu, "Steam Turbine")
        addMenuType(MenuTypes.oilWellMenu, "Oil Well")
        add(LangKeys.CONTAINER_OIL_DERRICK, "オイルデリック")
        add(LangKeys.CONTAINER_PUMPJACK, "パンプジャック")
        add(LangKeys.CONTAINER_RADAR, "レーダー")
        add(LangKeys.CONTAINER_REACTOR_MK0, "原子炉零号機")
        add(LangKeys.CONTAINER_REACTOR_MK2, "原子炉弐号機")
        addMenuType(MenuTypes.centrifugeMenu, "遠心分離装置")
        addMenuType(MenuTypes.rbmkRodMenu, "RBMK 燃料棒")
        add(LangKeys.CONTAINER_RBMK_REASIM_ROD, "RBMK 燃料棒 (ReaSim)")
        addMenuType(MenuTypes.rbmkBoilerMenu, "RBMK 蒸気経路")
        addMenuType(MenuTypes.rbmkManualControlMenu, "RBMK 制御棒")
        add(LangKeys.CONTAINER_RBMK_CONTROL_MODERATED, "RBMK 減速制御棒")
        addMenuType(MenuTypes.rbmkAutoControlMenu, "RBMK 自動制御棒")
        addMenuType(MenuTypes.rbmkConsoleMenu, "RBMK コンソール")

        addMenuType(MenuTypes.littleBoyMenu, "リトルボーイ")
        addMenuType(MenuTypes.fatManMenu, "ファットマン")

        addMenuType(MenuTypes.launchPadMenu, "ミサイル発射台")

        addDamageSource(DamageSources.extractBlood, "%1\$s ボブは人生の神髄を抜きすぎた。", "%1\$s は %2\$s のために、きちんと包装されたライフジュースを残そうとした。")
        addDamageSource(DamageSources.meteorite, "%1\$s は宇宙からの落石に当たった。", "%1\$s は %2\$s から逃れようとして、宇宙からの落石に当たった。")
        addDamageSource(DamageSources.murkyAnvil, "%1\$s は未定義です。", "%2\$s から逃げようとする %1\$s は未定義だった。")
        addDamageSource(DamageSources.nuclearBlast, "%1\$s は核爆発で吹き飛ばされた。", "%1\$s は %2\$s と戦っている間に核攻撃を受けた。 ")
        addDamageSource(DamageSources.radiation, "%1\$s は放射能中毒で死亡した。", "%1\$s は %2\$s との戦いで放射能中毒となった。")
        addDamageSource(DamageSources.shrapnel, "%1\$s は榴散弾でボロボロになった。", "%1\$s は %2\$s と戦っているときに榴散弾でボロボロになった。")

        addAttribute(Attributes.RADIATION_RESISTANCE, "放射線耐性")

        addFluidTrait(NTechFluidTraits.liquid, "Liquid")
        addFluidTrait(NTechFluidTraits.gaseous, "Gaseous")
        addFluidTrait(NTechFluidTraits.gaseousRoomTemp, "Gaseous at Room Temperature")
        addFluidTrait(NTechFluidTraits.plasma, "Plasma")
        addFluidTrait(NTechFluidTraits.antimatter, "Antimatter")
        addFluidTrait(NTechFluidTraits.delicious, "Delicious")
        addFluidTrait(NTechFluidTraits.combustible, "Combustible")
        addFluidTrait(NTechFluidTraits.coolable, "Coolable")
        addFluidTrait(NTechFluidTraits.corrosive, "Corrosive")
        addFluidTrait(NTechFluidTraits.flammable, "Flammable")
        addFluidTrait(NTechFluidTraits.heatable, "Heatable")
        addFluidTrait(NTechFluidTraits.radioactive, "Radioactive")
        addFluidTrait(NTechFluidTraits.toxic, "Toxic Fumes")

        add(LangKeys.ARMOR_BLAST_PROTECTION, "Damage modifier of %s against explosions")
        add(LangKeys.ARMOR_CUSTOM_GEIGER, "Built-In Geiger Counter HUD")
        add(LangKeys.ARMOR_DAMAGE_CAP, "Hard damage cap of %s")
        add(LangKeys.ARMOR_DAMAGE_MODIFIER, "General damage modifier of %s")
        add(LangKeys.ARMOR_DAMAGE_RESISTANCE_MODIFIER, "Damage modifier of %s against %s")
        add(LangKeys.ARMOR_DAMAGE_THRESHOLD, "Damage threshold of %s")
        add(LangKeys.ARMOR_DASH_COUNT, "Grants %s dashes")
        add(LangKeys.ARMOR_FIREPROOF, "Fireproof")
        add(LangKeys.ARMOR_FULL_SET_BONUS, "Full Set Bonus:")
        add(LangKeys.ARMOR_GEIGER_SOUND, "Auditory Geiger Counter")
        add(LangKeys.ARMOR_GRAVITY, "Gravity modifier of %s")
        add(LangKeys.ARMOR_HARD_LANDING, "Hard Landing")
        add(LangKeys.ARMOR_NULLIFIES_DAMAGE, "Nullifies all damage from %s")
        add(LangKeys.ARMOR_PROJECTILE_PROTECTION, "Damage modifier of %s against projectiles")
        add(LangKeys.ARMOR_PROTECTION_YIELD, "Protection applies to damage <%s")
        add(LangKeys.ARMOR_THERMAL, "Thermal Sight")
        add(LangKeys.ARMOR_VATS, "Enemy HUD")

        add(LangKeys.BUTTON_CANCEL, "Cancel")
        add(LangKeys.BUTTON_START, "Start")

        add(LangKeys.CHEMISTRY_URANIUM_HEXAFLUORIDE, "Uranium Hexafluoride Production")

        add(LangKeys.DETONATOR_INVALID_BLOCK_ENTITY, "Server Error: The target's BlockEntity is invalid!")
        add(LangKeys.DETONATOR_MISSING_COMPONENTS, "The explosive is missing components!")
        add(LangKeys.DETONATOR_NO_EXPLOSIVE, "Target is not a valid explosive!")
        add(LangKeys.DETONATOR_PROHIBITED, "The detonation was prohibited!")
        add(LangKeys.DETONATOR_SUCCESS, "Detonated!")
        add(LangKeys.DETONATOR_UNKNOWN_ERROR, "An unknown error occurred during the detonation")

        add(LangKeys.DEVICE_METEOR_REMOTE_WATCH_OUT, "Watch your head!")
        add(LangKeys.DEVICE_OIL_DETECTOR_BELOW, "Oil deposit directly below!")
        add(LangKeys.DEVICE_OIL_DETECTOR_NEAR, "Oil deposit detected nearby")
        add(LangKeys.DEVICE_OIL_DETECTOR_NO_OIL, "No oil detected")
        add(LangKeys.DEVICE_POSITION_SET, "Position set!")
        add(LangKeys.DEVICE_POSITION_NOT_LOADED, "Position is currently not loaded in the world!")
        add(LangKeys.DEVICE_POSITION_NOT_SET, "No position set!")

        add(LangKeys.ENERGY, "Energy")
        add(LangKeys.ENERGY_ENERGY_STORED, "Energy Stored: %s/%sHE")
        add(LangKeys.ENERGY_CHARGE_RATE, "Charge Rate: %sHE/t")
        add(LangKeys.ENERGY_DISCHARGE_RATE, "Discharge Rate: %sHE/t")

        add(LangKeys.EXPLOSION_SPAWNER_ERROR_EXTRA_FALLOUT, "Cannot parse extra fallout value")
        add(LangKeys.EXPLOSION_SPAWNER_ERROR_STRENGTH, "Cannot parse strength value")
        add(LangKeys.EXPLOSION_SPAWNER_EXTRA_FALLOUT, "Extra Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_HAS_FALLOUT, "Has Fallout")
        add(LangKeys.EXPLOSION_SPAWNER_MUTED, "Muted")
        add(LangKeys.EXPLOSION_SPAWNER_NO_PERMISSION, "Cannot use Nuclear Explosion Spawner: Insufficient permission")
        add(LangKeys.EXPLOSION_SPAWNER_POSITION, "Position")
        add(LangKeys.EXPLOSION_SPAWNER_STRENGTH, "Strength")

        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE, "Fuel grade: %s")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_AERO, "Aviation")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_GAS, "Gaseous")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_HIGH, "High")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_LOW, "Low")
        add(LangKeys.FLUID_TRAIT_COMBUSTIBLE_FUEL_GRADE_MEDIUM, "Medium")
        add(LangKeys.FLUID_TRAIT_COOLABLE_HEAT_EXCHANGER, "Coolable")
        add(LangKeys.FLUID_TRAIT_COOLABLE_TURBINE, "Turbine Steam")
        add(LangKeys.FLUID_TRAIT_CORROSIVE_STRONG, "Strongly Corrosive")
        add(LangKeys.FLUID_TRAIT_EFFICIENCY, "Efficiency: %s%%")
        add(LangKeys.FLUID_TRAIT_ENERGY_INFO, "Provides %s per bucket")
        add(LangKeys.FLUID_TRAIT_HEATABLE_BOILER, "Boilable")
        add(LangKeys.FLUID_TRAIT_HEATABLE_HEAT_EXCHANGER, "Heatable")

        add(LangKeys.GEIGER_CHUNK_RADIATION, "Current chunk radiation:")
        add(LangKeys.GEIGER_PLAYER_IRRADIATION, "Player irradiation:")
        add(LangKeys.GEIGER_PLAYER_RESISTANCE, "Player resistance:")
        add(LangKeys.GEIGER_TITLE, "GEIGER COUNTER")
        add(LangKeys.GEIGER_TOTAL_ENVIRONMENTAL_RADIATION, "Total environmental radiation:")

        add(LangKeys.HAZARD_ASBESTOS, "[Asbestos]")
        add(LangKeys.HAZARD_BLINDING, "[Blinding]")
        add(LangKeys.HAZARD_COAL, "[Coal Dust]")
        add(LangKeys.HAZARD_DIGAMMA, "[Digamma]")
        add(LangKeys.HAZARD_EXPLOSIVE, "[Flammable / Explosive]")
        add(LangKeys.HAZARD_HEAT, "[Pyrophoric / Hot]")
        add(LangKeys.HAZARD_HYDROREACTIVE, "[Hydroreactive]")
        add(LangKeys.HAZARD_RADIATON, "[Radioactive]")

        add(LangKeys.INFO_HOLD_KEY_FOR_INFO, "Hold %s to display more info")
        add(LangKeys.INFO_INPUT, "Input:")
        add(LangKeys.INFO_INPUTS, "Inputs:")
        add(LangKeys.INFO_ORE_CLUSTER, "Drops only when broken by a player")
        add(LangKeys.INFO_OUTPUT, "Output:")
        add(LangKeys.INFO_OUTPUTS, "Outputs:")
        add(LangKeys.INFO_POSITION, "Position: %d %d %d")
        add(LangKeys.INFO_PRODUCTION_TIME, "Production Time:")

        add(LangKeys.JEI_CATEGORY_ASSEMBLING, "Assembling")
        add(LangKeys.JEI_CATEGORY_BLASTING, "Blasting")
        add(LangKeys.JEI_CATEGORY_CHEMISTRY, "Chemistry")
        add(LangKeys.JEI_CATEGORY_CONSTRUCTING, "Constructing")
        add(LangKeys.JEI_CATEGORY_PRESSING, "Pressing")
        add(LangKeys.JEI_CATEGORY_SHREDDING, "Shredding")
        add(LangKeys.JEI_CATEGORY_SMITHING, "Smithing")
        add(LangKeys.JEI_CATEGORY_TEMPLATE_FOLDER, "Template Folder")
        add(LangKeys.JEI_EXPERIENCE, "%s XP")
        add(LangKeys.JEI_OUTPUT_CHANCE, "Output chance:")
        add(LangKeys.JEI_TIER_MINIMUM, "Minimum Tier: %s")
        add(LangKeys.JEI_TIER_RANGE, "Tier Range: %s..%s")

        add(LangKeys.OIL_WELL_STATUS_OK, "Status: Ok")
        add(LangKeys.OIL_WELL_STATUS_NO_OIL_SOURCE, "Status: No oil source")
        add(LangKeys.OIL_WELL_STATUS_ERROR, "Status: Can't operate")
        add(LangKeys.OIL_WELL_STATUS_OUT_OF_FLUID, "Status: Out of fracking solution")
        add(LangKeys.OIL_WELL_STATUS_LOOKING_FOR_OIL, "Status: Looking for oil")
        add(LangKeys.OIL_WELL_STATUS_NO_POWER, "Status: No power")

        add(LangKeys.RBMK_BOILER_STEAM, "Steam: %d / %d")
        add(LangKeys.RBMK_BOILER_TYPE, "Compressor: %s")
        add(LangKeys.RBMK_BOILER_WATER, "Feedwater: %d / %d")
        add(LangKeys.RBMK_BURN_EULER, "SAFE / EULER")
        add(LangKeys.RBMK_BURN_LINEAR, "DANGEROUS / LINEAR")
        add(LangKeys.RBMK_BURN_LOGARITHMIC, "MEDIUM / LOGARITHMIC")
        add(LangKeys.RBMK_BURN_NEGATIVE_QUADRATIC, "DANGEROUS / NEGATIVE-QUADRATIC")
        add(LangKeys.RBMK_BURN_PASSIVE, "SAFE / PASSIVE")
        add(LangKeys.RBMK_BURN_QUADRATIC, "DANGEROUS / QUADRATIC")
        add(LangKeys.RBMK_BURN_SIGMOID, "SAFE / SIGMOID")
        add(LangKeys.RBMK_BURN_SINE_SLOPE, "EXPERIMENTAL / SINE SLOPE")
        add(LangKeys.RBMK_BURN_SQUARE_ROOT, "MEDIUM / SQUARE ROOT")
        add(LangKeys.RBMK_CONSOLE_ASSIGN, "Assign selected columns to screen #%d")
        add(LangKeys.RBMK_CONSOLE_DESELECT_CONTROL_RODS, "Deselect all")
        add(LangKeys.RBMK_CONSOLE_LINK, "RBMK linked!")
        add(LangKeys.RBMK_CONSOLE_SELECT_CONTROL_RODS, "Select all control rods")
        add(LangKeys.RBMK_CONSOLE_SELECT_GROUP, "Select %s group")
        add(LangKeys.RBMK_CONTROL_GROUP_BLUE, "§1Blue Group")
        add(LangKeys.RBMK_CONTROL_GROUP_GREEN, "§aGreen Group")
        add(LangKeys.RBMK_CONTROL_GROUP_PURPLE, "§5Purple Group")
        add(LangKeys.RBMK_CONTROL_GROUP_RED, "§cRed Group")
        add(LangKeys.RBMK_CONTROL_GROUP_YELLOW, "§eYellow Group")
        add(LangKeys.RBMK_CONTROL_ROD_LEVEL, "%.1f%%")
        add(LangKeys.RBMK_HEAT, "Column Temperature: %.1f°C")
        add(LangKeys.RBMK_MODERATED, "Moderated")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE, "Draconic Flames")
        add(LangKeys.RBMK_NAME_PELLET_BALEFIRE_GOLD, "Antihydrogen in a Magnetized Gold-198 Lattice")
        add(LangKeys.RBMK_NAME_PELLET_DRX, "§kcan't you hear, can't you hear the thunder?")
        add(LangKeys.RBMK_NAME_PELLET_FLASHLEAD, "Antihydrogen confined by a Magnetized Gold-198 and Lead-209 Lattice")
        add(LangKeys.RBMK_NAME_PELLET_HEA241, "Highly Enriched Americium-241")
        add(LangKeys.RBMK_NAME_PELLET_HEA242, "Highly Enriched Americium-242")
        add(LangKeys.RBMK_NAME_PELLET_HEAUS, "Highly Enriched Australium (Ayerite)")
        add(LangKeys.RBMK_NAME_PELLET_HEN, "Highly Enriched Neptunium-237")
        add(LangKeys.RBMK_NAME_PELLET_HEP239, "Highly Enriched Plutonium-239")
        add(LangKeys.RBMK_NAME_PELLET_HEP241, "Highly Enriched Plutonium-241")
        add(LangKeys.RBMK_NAME_PELLET_HES, "Highly Enriched Schrabidium-326")
        add(LangKeys.RBMK_NAME_PELLET_HEU233, "Highly Enriched Uranium-233")
        add(LangKeys.RBMK_NAME_PELLET_HEU235, "Highly Enriched Uranium-235")
        add(LangKeys.RBMK_NAME_PELLET_LEA, "Low Enriched Americium-242")
        add(LangKeys.RBMK_NAME_PELLET_LEAUS, "Low Enriched Australium (Tasmanite)")
        add(LangKeys.RBMK_NAME_PELLET_LEP, "Low Enriched Plutonium-239")
        add(LangKeys.RBMK_NAME_PELLET_LES, "Low Enriched Schrabidium-326")
        add(LangKeys.RBMK_NAME_PELLET_MEA, "Medium Enriched Americium-242")
        add(LangKeys.RBMK_NAME_PELLET_MEN, "Medium Enriched Neptunium-237")
        add(LangKeys.RBMK_NAME_PELLET_MEP, "Medium Enriched Plutonium-239")
        add(LangKeys.RBMK_NAME_PELLET_MES, "Medium Enriched Schrabidium-326")
        add(LangKeys.RBMK_NAME_PELLET_MEU, "Medium Enriched Uranium-235")
        add(LangKeys.RBMK_NAME_PELLET_MOX, "Mixed MEU & LEP Oxide")
        add(LangKeys.RBMK_NAME_PELLET_PO210BE, "Polonium-210 & Beryllium Neutron Source")
        add(LangKeys.RBMK_NAME_PELLET_PU238BE, "Plutonium-238 & Beryllium Neutron Source")
        add(LangKeys.RBMK_NAME_PELLET_RA226BE, "Radium-226 & Beryllium Neutron Source")
        add(LangKeys.RBMK_NAME_PELLET_THMEU, "Thorium with MEU Driver Fuel")
        add(LangKeys.RBMK_NAME_PELLET_UEU, "Unenriched Uranium")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_AM_MIX, "Zirconium Fast Breeder - HEP-241#MEA")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_BISMUTH, "Zirconium Fast Breeder - LEU/HEP-241#Bi")
        add(LangKeys.RBMK_NAME_PELLET_ZFB_PU241, "Zirconium Fast Breeder - HEU-235/HEP-240#Pu-241")
        add(LangKeys.RBMK_NEUTRON_FAST, "Fast Neutrons")
        add(LangKeys.RBMK_NEUTRON_SLOW, "Slow Neutrons")
        add(LangKeys.RBMK_NEUTRON_ANY, "All Neutrons")
        add(LangKeys.RBMK_PELLET_DEPLETION_FULL, "Fully Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_HIGH, "Highly Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_MODERATE, "Moderately Depleted")
        add(LangKeys.RBMK_PELLET_DEPLETION_NEW, "Brand New")
        add(LangKeys.RBMK_PELLET_DEPLETION_SLIGHT, "Barely Depleted")
        add(LangKeys.RBMK_PELLET_XENON_POISONED, "High Xenon Poison")
        add(LangKeys.RBMK_PELLET_RECYCLE, "Pellet for recycling")
        add(LangKeys.RBMK_ROD_DEPLETION, "Depletion: %.3f%%")
        add(LangKeys.RBMK_ROD_DIFFUSION, "Diffusion: %s")
        add(LangKeys.RBMK_ROD_FLUX_FUNC, "Flux function: %s")
        add(LangKeys.RBMK_ROD_FUNC_TYPE, "Function type: %s")
        add(LangKeys.RBMK_ROD_HEAT, "Heat per flux: %s")
        add(LangKeys.RBMK_ROD_HEAT_CORE, "Core temp: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL, "Skin temp: %.1f°C")
        add(LangKeys.RBMK_ROD_HEAT_HULL_TO_MELTING_POINT, "Skin temp: %.1f°C / %.1f°C")
        add(LangKeys.RBMK_ROD_MELTING_POINT, "Melting point: %s")
        add(LangKeys.RBMK_ROD_SOURCE, "Self-igniting")
        add(LangKeys.RBMK_ROD_SPLITS_INTO, "Splits into: %s")
        add(LangKeys.RBMK_ROD_SPLITS_WITH, "Splits with: %s")
        add(LangKeys.RBMK_ROD_XENON, "Xenon poison: %.3f%%")
        add(LangKeys.RBMK_ROD_XENON_BURN, "Xenon burn function: %s")
        add(LangKeys.RBMK_ROD_XENON_GEN, "Xenon gen function: %s")
        add(LangKeys.RBMK_SCREEN_DEPLETION, "Depl: %.1f%%")
        add(LangKeys.RBMK_SCREEN_FUEL_TEMPERATURE, "Core: %.1f°C")
        add(LangKeys.RBMK_SCREEN_POISON, "Xenon: %.1f%%")
        add(LangKeys.RBMK_SCREEN_ROD_EXTRACTION, "Control: %.1f%%")
        add(LangKeys.RBMK_SCREEN_TEMPERATURE, "Temp: %.1f°C")
        add(LangKeys.RBMK_SCREEN_TYPE_COLUMN_TEMPERATURE, "Monitor average column temperature")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_DEPLETION, "Monitor average fuel depletion")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_POISON, "Monitor average xenon poisoning")
        add(LangKeys.RBMK_SCREEN_TYPE_FUEL_TEMPERATURE, "Monitor average fuel temperature")
        add(LangKeys.RBMK_SCREEN_TYPE_NONE, "Off")
        add(LangKeys.RBMK_SCREEN_TYPE_ROD_EXTRACTION, "Monitor average control rod extraction")

        add(LangKeys.SIREN_TRACK_LOOP, "Type: Loop")
        add(LangKeys.SIREN_TRACK_ONCE, "Type: Play Once")
        add(LangKeys.SIREN_TRACK_RANGE, "Range: %s Meters")
        add(LangKeys.SIREN_TRACK_SIREN_TRACK, "Siren Track")

        add(LangKeys.SUBTITLE_ANVIL_FALL, "Anvil clashes")
        add(LangKeys.SUBTITLE_ASSEMBLER_OPERATE, "Assembler whirs")
        add(LangKeys.SUBTITLE_BLEEP, "Device bleeps")
        add(LangKeys.SUBTITLE_BLOCK_DEBRIS, "Debris hit the ground")
        add(LangKeys.SUBTITLE_BOOP, "Device boops")
        add(LangKeys.SUBTITLE_CENTRIFUGE_OPERATE, "Centrifuge hums")
        add(LangKeys.SUBTITLE_CHEM_PLANT_OPERATE, "Chemical Plant operates")
        add(LangKeys.SUBTITLE_GEIGER_CLICK, "Geiger Counter clicks")
        add(LangKeys.SUBTITLE_ITEM_INJECT, "Needle injected")
        add(LangKeys.SUBTITLE_ITEM_UNPACK, "Item unpacked")
        add(LangKeys.SUBTITLE_METEOR_IMPACT, "Meteor strikes")
        add(LangKeys.SUBTITLE_MINI_NUKE_EXPLODE, "Mini nuke explodes")
        add(LangKeys.SUBTITLE_MISSILE_TAKEOFF, "Missile takes off")
        add(LangKeys.SUBTITLE_PRESS_OPERATE, "Press stamps")
        add(LangKeys.SUBTITLE_RBMK_AZ5_COVER, "AZ-3 lid opened")
        add(LangKeys.SUBTITLE_RBMK_EXPLODE, "RBMK explodes")
        add(LangKeys.SUBTITLE_RBMK_SHUTDOWN, "RBMK shutting down")
        add(LangKeys.SUBTITLE_SIREN_AIR_RAID, "Siren running: Air Raid Siren")
        add(LangKeys.SUBTITLE_SIREN_AMS, "Siren running: AMS Siren")
        add(LangKeys.SUBTITLE_SIREN_APC, "Siren running: APC Siren")
        add(LangKeys.SUBTITLE_SIREN_APC_PASS, "Siren running: APC Pass")
        add(LangKeys.SUBTITLE_SIREN_AUTOPILOT_DISCONNECTED, "Siren running: Autopilot Disconnected")
        add(LangKeys.SUBTITLE_SIREN_BANK, "Siren running: Bank Alarm")
        add(LangKeys.SUBTITLE_SIREN_BEEP, "Siren running: Beep Siren")
        add(LangKeys.SUBTITLE_SIREN_BLAST_DOOR, "Siren running: Blast Door Alarm")
        add(LangKeys.SUBTITLE_SIREN_CLASSIC, "Siren running: Classic Siren")
        add(LangKeys.SUBTITLE_SIREN_CONTAINER, "Siren running: Container Alarm")
        add(LangKeys.SUBTITLE_SIREN_EAS, "Siren running: EAS Alarm Screech")
        add(LangKeys.SUBTITLE_SIREN_HATCH, "Siren running: Hatch Siren")
        add(LangKeys.SUBTITLE_SIREN_KLAXON, "Siren running: Klaxon")
        add(LangKeys.SUBTITLE_SIREN_MISSILE_SILO, "Siren running: Missile Silo Siren")
        add(LangKeys.SUBTITLE_SIREN_NOSTROMO_SELF_DESTRUCT, "Siren running: Nostromo Self Destruct")
        add(LangKeys.SUBTITLE_SIREN_RAZORTRAIN_HORN, "Siren running: Razortrain Horn")
        add(LangKeys.SUBTITLE_SIREN_SECURITY, "Siren running: Security Alert")
        add(LangKeys.SUBTITLE_SIREN_STANDARD, "Siren running: Standard Siren")
        add(LangKeys.SUBTITLE_SIREN_SWEEP, "Siren running: Sweep Siren")
        add(LangKeys.SUBTITLE_SIREN_VAULT_DOOR, "Siren running: Vault Door Alarm")
        add(LangKeys.SUBTITLE_UPGRADE_INSTALL, "Upgrade installed")
        add(LangKeys.SUBTITLE_USE_RADAWAY, "Liquid infused")

        add(LangKeys.UPGRADE_INFO_ACCEPTED_UPGRADES, "Accepted Upgrades:")
        add(LangKeys.UPGRADE_INFO_BURN_GAS, "Burn %smB of gas for %s")
        add(LangKeys.UPGRADE_INFO_CONSUMPTION, "Consumption: %s")
        add(LangKeys.UPGRADE_INFO_DELAY, "Delay: %s")
        add(LangKeys.UPGRADE_INFO_STACKS_TO, "Stacks to level %s")
        add(LangKeys.UPGRADE_NAME_AFTER_BURNER, "Afterburner")
        add(LangKeys.UPGRADE_NAME_OVERDRIVE, "Overdrive")
        add(LangKeys.UPGRADE_NAME_POWER_SAVING, "Power Saving")
        add(LangKeys.UPGRADE_NAME_SPEED, "Speed")
        add(LangKeys.UPGRADE_WARN_INCOMPATIBLE, "This upgrade is incompatible!")
        add(LangKeys.UPGRADE_WARN_MACHINE_NOT_UPGRADEABLE, "This machine is not upgradeable!")
        add(LangKeys.UPGRADE_WARN_NOT_A_MACHINE, "This is not a machine!")
        add(LangKeys.UPGRADE_WARN_VIEW_MACHINE, "View a machine for info about effects")
        add(LangKeys.UPGRADE_WARN_UNKNOWN_COMPATIBILITY, "Compatibility with the machine is unknown")

        add(LangKeys.VERSION_CHECKER_ANNOUNCEMENT, "-- NTM Version Checker --")
        add(LangKeys.VERSION_CHECKER_BLEEDING_EDGE, "Running on the bleeding edge!")
        add(LangKeys.VERSION_CHECKER_CHANGES_LIST, "Short list of changes:")
        add(LangKeys.VERSION_CHECKER_CUTTING_EDGE, "Running on the cutting edge of beta!")
        add(LangKeys.VERSION_CHECKER_UPDATE, "There's a newer version of NTM available!")
        add(LangKeys.VERSION_CHECKER_VIEW_RELEASES, "Click here to get to the releases page!")

        add(LangKeys.VOLCANO_EXTINGUISHING, "DOES EXTINGUISH")
        add(LangKeys.VOLCANO_GROWING, "DOES GROW")
        add(LangKeys.VOLCANO_NOT_EXTINGUISHING, "DOES NOT EXTINGUISH")
        add(LangKeys.VOLCANO_NOT_GROWING, "DOES NOT GROW")
        add(LangKeys.VOLCANO_SMOLDERING, "SHIELD VOLCANO")

        add(LangKeys.WORD_SECONDS, "Seconds")
    }

    private fun addMaterials() = with(Materials) {
        addMaterial(coal, "Coal")
        addMaterial(iron, "Iron")
        addMaterial(copper, "Copper")
        addMaterial(gold, "Gold")
        addMaterial(redstone, "Redstone")
        addMaterial(emerald, "Emerald")
        addMaterial(lazuli, "Lapis Lazuli")
        addMaterial(diamond, "Diamond")

        addMaterial(actinium227, "Actinium-227")
        addMaterial(advancedAlloy, "Advanced Alloy")
        addMaterial(aluminium, "Aluminium")
        addMaterial(americium241, "Americium-241")
        addMaterial(americium242, "Americium-242")
        addMaterial(americiumFuel, "Americium Fuel")
        addMaterial(arsenic, "Arsenic")
        addMaterial(asbestos, "Asbestos")
        addMaterial(australium, "Australium")
        addMaterial(bakelite, "Bakelite")
        addMaterial(beryllium, "Beryllium")
        addMaterial(bismuth, "Bismuth")
        addMaterial(boron, "Boron")
        addMaterial(cobalt, "Cobalt")
        addMaterial(cobalt60, "Cobalt-60")
        addMaterial(combineSteel, "Combine Steel")
        addMaterial(daffergon, "Daffergon")
        addMaterial(desh, "Desh")
        addMaterial(dineutronium, "Dineutronium")
        addMaterial(electronium, "Electronium")
        addMaterial(euphemium, "Euphemium")
        addMaterial(ferricSchrabidate, "Ferric Schrabidate")
        addMaterial(fiberglass, "Fiberglass")
        addMaterial(fluorite, "Fluorite")
        addMaterial(ghiorsium336, "Ghiorsium-336")
        addMaterial(gold198, "Gold-198")
        addMaterial(graphite, "Graphite")
        addMaterial(hesFuel, "Highly Enriched Schrabidium Fuel")
        addMaterial(highSpeedSteel, "High-Speed Steel")
        addMaterial(insulator, "Insulator")
        addMaterial(lanthanum, "Lanthanum")
        addMaterial(lead, "Lead")
        addMaterial(lead209, "Lead-209")
        addMaterial(lesFuel, "Low Enriched Schrabidium Fuel")
        addMaterial(lignite, "Lignite")
        addMaterial(lithium, "Lithium")
        addMaterial(magnetizedTungsten, "Magnetized Tungsten")
        addMaterial(moxFuel, "MOX Fuel")
        addMaterial(naturalPlutonium, "Plutonium")
        addMaterial(naturalUranium, "Uranium")
        addMaterial(neptunium, "Neptunium")
        addMaterial(neptuniumFuel, "Neptunium Fuel")
        addMaterial(niobium, "Niobium")
        addMaterial(niter, "Niter")
        addMaterial(nuclearWaste, "Nuclear Waste")
        addMaterial(osmiridium, "Osmiridium")
        addMaterial(plutonium238, "Plutonium-238")
        addMaterial(plutonium239, "Plutonium-239")
        addMaterial(plutonium240, "Plutonium-240")
        addMaterial(plutonium241, "Plutonium-241")
        addMaterial(plutoniumFuel, "Plutonium Fuel")
        addMaterial(polonium, "Polonium")
        addMaterial(polymer, "Polymer")
        addMaterial(radium226, "Radium-226")
        addMaterial(reactorGradeAmericium, "Reactor Grade Americium")
        addMaterial(reactorGradePlutonium, "Reactor Grade Plutonium")
        addMaterial(redCopper, "Red Copper")
        addMaterial(redPhosphorus, "Red Phosphorus")
        addMaterial(reiium, "Reiium")
        addMaterial(rubber, "Rubber")
        addMaterial(saturnite, "Saturnite")
        addMaterial(schrabidium, "Schrabidium")
        addMaterial(schrabidiumFuel, "Schrabidium Fuel")
        addMaterial(schraranium, "Schraranium")
        addMaterial(solinium, "Solinium")
        addMaterial(starmetal, "Starmetal")
        addMaterial(steel, "Steel")
        addMaterial(strontium90, "Strontium-90")
        addMaterial(sulfur, "Sulfur")
        addMaterial(tantalium, "Tantalium")
        addMaterial(technetium99, "Technetium-99")
        addMaterial(technetiumSteel, "Technetium Steel")
        addMaterial(thorium, "Thorium-232")
        addMaterial(thoriumFuel, "Thorium Fuel")
        addMaterial(titanium, "Titanium")
        addMaterial(trinitite, "Trinitite")
        addMaterial(tungsten, "Tungsten")
        addMaterial(unobtainium, "Unobtainium")
        addMaterial(uranium233, "Uranium-233")
        addMaterial(uranium235, "Uranium-235")
        addMaterial(uranium238, "Uranium-238")
        addMaterial(uraniumFuel, "Uranium Fuel")
        addMaterial(verticium, "Verticium")
        addMaterial(weidanium, "Weidanium")
        addMaterial(whitePhosphorus, "White Phosphorus")
        addMaterial(yellowcake, "イエローケーキ")
    }

    override val spawnEggFormat = "%sのスポーンエッグ"

    override val oreFormat = "%s鉱石"
    override val deepOreFormat = "深層%s鉱石"
    override val blockFormat = "%sブロック"
    override val rawFormat = "%sの原石"
    override val ingotFormat = "%sインゴット"
    override val billetFormat = "%sビレット"
    override val nuggetFormat = "%sの塊"
    override val crystalsFormat = "%sクリスタル"
    override val powderFormat = "%sの粉"
    override val plateFormat = "%sの板"
    override val wireFormat = "%sのワイヤー"
}
